- includes/class-newspack-ads-blocks.php
- includes/class-newspack-ads-model.php
- includes/class-newspack-ads-widget.php
- includes/class-newspack-ads.php
- src/blocks/ad-unit/edit.js
- src/blocks/ad-unit/view.php
- tests/unit-tests/class-newspack-ads-tests-model.php
Complete testing instructions in https://github.com/Automattic/newspack-plugin/pull/375.
Closes https://github.com/Automattic/newspack-ads/issues/14, https://github.com/Automattic/newspack-ads/issues/13.
> Ad Model Improvements

- .gitignore
- package-lock.json
- package.json
This PR adds an npm release script to the plugin, that packages up a .zip for release.
1. Run `npm install`
2. Run `npm run release:archive`
3. Verify the release has been built in `release/newspack-ads.zip`
4. Verify all files are present in the zip.
> Add A Release Script

- includes/class-newspack-ads-blocks.php
- includes/class-newspack-ads-model.php
- package-lock.json
> Release 3/31/2020

- includes/class-newspack-ads-blocks.php
> Release 23/06/2020

- includes/suppress-ads.php
* Add a filter to control whether ads should be displayed
> Release - June 30, 2020

- includes/class-newspack-ads-blocks.php
- includes/suppress-ads.php
> Release 07/07/2020

- .circleci/config.yml
- bin/install-wp-tests.sh
Fixes PHP tests on CI. Closes #48.
See that `test-php` CI job is passing 👇﻿
> Fix PHP tests

- .circleci/config.yml
- bin/install-wp-tests.sh
> Release Jul 22

- .circleci/config.yml
- bin/install-wp-tests.sh
> Release Aug 04

- includes/class-newspack-ads-blocks.php
- includes/class-newspack-ads-model.php
> Alpha release Aug 18

- includes/class-newspack-ads-blocks.php
- includes/class-newspack-ads-model.php
> Release Aug 18

- .circleci/config.yml
- includes/class-newspack-ads-blocks.php
- includes/class-newspack-ads-model.php
- package-lock.json
> Alpha release Sep 15

- .circleci/config.yml
- includes/class-newspack-ads-blocks.php
- includes/class-newspack-ads-model.php
- package-lock.json
> Release Sep 15

- includes/class-newspack-ads-model.php
- package-lock.json
> Alpha release Sep 29

- includes/class-newspack-ads-model.php
- package-lock.json
> Release Sep 29

- .gitignore
- package-lock.json
- package.json
- src/blocks/ad-unit/index.js
- src/setup/newspack-logo.js
> Alpha release Dec 08

- .gitignore
- package-lock.json
- package.json
- src/blocks/ad-unit/index.js
- src/setup/newspack-logo.js
> Release – Dec. 8

- includes/class-newspack-ads-blocks.php
This PR improves the way responsive ad handling works in non-AMP mode. It does so by using a somewhat simple heuristic:
- If an ad has sizes both smaller and larger than 500px wide, that ad is almost certainly a responsive ad with desktop and mobile sizes.
- On desktops, if there is a desktop-sized ad defined, don't show any mobile-sized ads.
- Otherwise, logic is the same as before.
This explanation makes more sense with some examples:
- Consider an ad with two sizes: `[[728, 90], [320, 50]]`. This is without a doubt, a responsive ad with a mobile and desktop size. On viewports >= 728px wide, we should display the `[728, 90]` ad. On viewports < 728px wide, we should display the `[320,50]` ad.
- Consider an ad with one size: `[[728,90]]`. This ad should only be shown on viewports >= …
> Improve responsive ad handling in non-AMP mode

- includes/class-newspack-ads-model.php
Right now, if an ad unit isn't responsive, we display only the largest available ad unit size. Sticky ads use `amp-sticky-ad`, which only supports a single child of `amp-ad`, and therefore can't be responsive. But the primary use case is for mobile devices, so we generally want to be showing the _smallest_ size available for that placement. This branch does exactly that, for sticky ads only. Other placements will still show the largest available size.
We may want to consider adding CSS to the theme to hide the sticky ad unit at viewports larger than mobile size—what do you think, @claudiulodro?
To test:
1. While on `master`, in the Newspack > Advertising wizard, enable Google Ad Manager and use the Newspack network code (ping me for the code if you need it).
2. Create an ad unit with the …
> fix: for sticky ads, use smallest ad unit size available

- includes/class-newspack-ads-model.php
> Alpha release Jan 28

- includes/class-newspack-ads-model.php
> Release Jan 28

- includes/class-newspack-ads-model.php
> Alpha release Feb 23

- includes/class-newspack-ads-model.php
> Release Feb 24

- .github/workflows/main.yml
So we have less clicking to do
> Add PR labelling workflow

- .github/workflows/main.yml
> Release Apr 06

- package-lock.json
- package.json
> Release Apr 27

- includes/class-newspack-ads-model.php
> Alpha release Jun 01

- includes/class-newspack-ads-model.php
> Release Jun 01

- .circleci/config.yml
> fix: run composer install on release tasks

- includes/class-newspack-ads-widget.php
> Alpha release Jul 06

- includes/class-newspack-ads-widget.php
> Release Jul 06

- includes/class-newspack-ads-model.php
> Alpha release Jul 13

- includes/class-newspack-ads-model.php
> Release Jul 13

- includes/class-newspack-ads-model.php
- includes/class-newspack-ads-widget.php
> Alpha release Jul 19

- includes/class-newspack-ads-model.php
- includes/class-newspack-ads-widget.php
> Release Jul 19

- includes/class-newspack-ads-gam.php
With the amount of red tape around a multi-site OAuth setup, it's easier to use Service Accounts.
After these changes, a GAM instance will be linked to Newspack not via OAuth flow, but via a Service Account flow:
1. Newspack creates a new service account
2. Publisher add the service account to their GAM instance 
3. Newspack places the JSON credentials file on publisher's WP instance
1. Create a Google Cloud Platform app and create a Service Account*
2. The service account has an email address. [Add it to a GAM instance](https://support.google.com/admanager/answer/6078734?hl=en).
3. Ensure Newspack's Google OAuth is turned off (or unset - `NEWSPACK_ADS_USE_GAM`)
4. Visit the Ads wizard, GAM configuration and observe the "legacy" view (the ad units should not have a toggle switch)
3. …
> feat(gam): connect using a service account

- includes/class-newspack-ads-gam.php
A new alpha release, so that GAM service account flow can be tested.
> Alpha release Sep 01

- includes/class-newspack-ads-model.php
> Alpha release Sep 07

- includes/class-newspack-ads-gam.php
- includes/class-newspack-ads-model.php
> Release Sep 08

- includes/class-newspack-ads-model.php
A new alpha release to get https://github.com/Automattic/newspack-ads/pull/178 out.
> Alpha release Sep 16

- includes/class-newspack-ads-gam.php
- includes/class-newspack-ads-model.php
> Alpha release Sep 21

- includes/class-newspack-ads-gam.php
- includes/class-newspack-ads-model.php
- tests/test-model.php
> Alpha release Sep 22

- includes/class-newspack-ads-gam.php
- includes/class-newspack-ads-model.php
- tests/test-model.php
> Release Sep 22

- .circleci/config.yml
> Release Nov 02

- includes/class-newspack-ads-blocks.php
- includes/class-newspack-ads-gam.php
- includes/class-newspack-ads-model.php
- includes/class-newspack-ads-settings.php
- includes/class-newspack-ads.php
- tests/test-settings.php
> Alpha release Nov 09

- includes/class-newspack-ads-blocks.php
- includes/class-newspack-ads-gam.php
- includes/class-newspack-ads-model.php
- includes/class-newspack-ads-settings.php
- includes/class-newspack-ads.php
- tests/test-settings.php
> Release Nov 09

- .circleci/config.yml
- includes/class-newspack-ads-gam.php
- includes/class-newspack-ads-model.php
- includes/class-newspack-ads-scaip.php
- includes/class-newspack-ads-settings.php
- includes/class-newspack-ads.php
> Alpha release Nov 16

- .circleci/config.yml
- CHANGELOG.md
- includes/class-newspack-ads-gam.php
- includes/class-newspack-ads-model.php
- includes/class-newspack-ads-scaip.php
- includes/class-newspack-ads-settings.php
- includes/class-newspack-ads.php
- newspack-ads.php
- package-lock.json
- package.json
> Release Nov 18

- includes/class-newspack-ads-placements.php
- includes/class-newspack-ads-sidebar-placements.php
- includes/class-newspack-ads.php
- includes/suppress-ads.php
> Alpha release Nov 18

- includes/class-newspack-ads-gam.php
- includes/class-newspack-ads-model.php
> Alpha release Dec 09

- includes/bidders/class-newspack-ads-bidder-medianet.php
- includes/class-newspack-ads-bidding.php
- includes/class-newspack-ads-blocks.php
- includes/class-newspack-ads-model.php
- includes/class-newspack-ads-placements.php
- includes/class-newspack-ads-settings.php
- includes/class-newspack-ads-widget.php
- includes/class-newspack-ads.php
- package-lock.json
- package.json
- src/prebid/index.js
- tests/test-bidding.php
- tests/test-settings.php
- webpack.config.js
> Alpha release Dec 10

- includes/class-newspack-ads-bidding.php
- package-lock.json
- package.json
- src/prebid/index.js
- webpack.config.js
> Alpha release Dec 13

- CHANGELOG.md
- includes/bidders/class-newspack-ads-bidder-medianet.php
- includes/class-newspack-ads-bidding.php
- includes/class-newspack-ads-blocks.php
- includes/class-newspack-ads-gam.php
- includes/class-newspack-ads-model.php
- includes/class-newspack-ads-placements.php
- includes/class-newspack-ads-settings.php
- includes/class-newspack-ads-widget.php
- includes/class-newspack-ads.php
- newspack-ads.php
- package-lock.json
- package.json
- src/prebid/index.js
- tests/test-bidding.php
- tests/test-settings.php
- webpack.config.js
> Release Dec 14

- includes/class-newspack-ads-bidding.php
- includes/class-newspack-ads-placements.php
- includes/class-newspack-ads-sidebar-placements.php
> Alpha release Dec 15

- CHANGELOG.md
- includes/class-newspack-ads-bidding.php
- includes/class-newspack-ads-placements.php
- includes/class-newspack-ads-sidebar-placements.php
- newspack-ads.php
- package-lock.json
- package.json
> Release Dec 15

- .github/workflows/auto-merge.yml
- composer.json
- composer.lock
- includes/class-newspack-ads-bidding.php
- includes/class-newspack-ads-gam.php
- includes/class-newspack-ads-placements.php
- includes/class-newspack-ads-sidebar-placements.php
> Alpha release Jan 06

- includes/class-newspack-ads-gam.php
GAM Ad unit creation does not have API error handling implemented. This PR implements error handling for API update/create methods with generic messaging and specific messaging for the reported "not unique" error.
Closes #275 
1. While on the master branch, follow the steps in #275 to confirm the issue
2. Check out this branch and https://github.com/Automattic/newspack-plugin/pull/1424
3. Run `npm run build` for `newspack-plugin`
4. Attempt to create the ad unit with the same name again and confirm you are not redirected to the inventory and the appropriate error message appears on the top of the page.
> fix: ad unit error handling

- .circleci/config.yml
- .github/CODEOWNERS
- includes/class-newspack-ads-gam.php
- includes/class-newspack-ads-placements.php
> Alpha release Jan 18

- .circleci/config.yml
- .github/CODEOWNERS
- .github/workflows/auto-merge.yml
- CHANGELOG.md
- composer.json
- composer.lock
- includes/class-newspack-ads-bidding.php
- includes/class-newspack-ads-gam.php
- includes/class-newspack-ads-placements.php
- includes/class-newspack-ads-sidebar-placements.php
- newspack-ads.php
- package-lock.json
- package.json
> Release Jan 18

- includes/class-newspack-ads-bidding-gam.php
- includes/class-newspack-ads-bidding.php
- includes/class-newspack-ads-custom-label.php
- includes/class-newspack-ads-gam.php
- includes/class-newspack-ads-placements.php
- includes/class-newspack-ads-scaip.php
- includes/class-newspack-ads-settings.php
- includes/class-newspack-ads.php
- package-lock.json
- package.json
- src/wizard-settings/header-bidding-gam/index.js
- src/wizard-settings/header-bidding-gam/style.scss
- webpack.config.js
> Alpha release Jan 31

- CHANGELOG.md
- includes/bidders/class-newspack-ads-bidder-medianet.php
- includes/bidders/class-newspack-ads-bidder-openx.php
- includes/bidders/class-newspack-ads-bidder-pubmatic.php
- includes/bidders/class-newspack-ads-bidder-sovrn.php
- includes/class-newspack-ads-bidding.php
- includes/class-newspack-ads-gam.php
- includes/class-newspack-ads-model.php
- includes/class-newspack-ads-settings.php
- includes/class-newspack-ads.php
- newspack-ads.php
- package-lock.json
- package.json
- src/prebid/index.js
- src/wizard-settings/header-bidding-gam/index.js
- tests/test-bidding.php
> Release Feb 22

- includes/class-newspack-ads-custom-label.php
- includes/class-newspack-ads-settings.php
- includes/class-newspack-ads-sidebar-placements.php
Quick PR to add capitalisation to the labels
> Capitalise labels

- includes/integrations/class-ad-refresh-control.php
- package-lock.json
- package.json
> Alpha release Apr 05

- composer.lock
- includes/class-bidding.php
- includes/class-blocks.php
- includes/class-core.php
- includes/class-placements.php
- includes/class-providers.php
- includes/class-suppression.php
- includes/customizer/class-customizer.php
- includes/customizer/class-placement-customize-control.php
- includes/providers/gam/class-gam-model.php
- includes/utils.php
- package-lock.json
- package.json
- src/blocks/ad-unit/edit.js
- src/blocks/ad-unit/index.js
- src/customizer/control.js
- src/customizer/preview.js
- src/customizer/preview.scss
- src/frontend/style.scss
- webpack.config.js
> Alpha release May 02

- CHANGELOG.md
- composer.lock
- includes/class-bidding.php
- includes/class-blocks.php
- includes/class-core.php
- includes/class-placements.php
- includes/class-providers.php
- includes/class-suppression.php
- includes/customizer/class-customizer.php
- includes/customizer/class-placement-customize-control.php
- includes/providers/gam/class-gam-model.php
- includes/utils.php
- newspack-ads.php
- package-lock.json
- package.json
- src/blocks/ad-unit/edit.js
- src/blocks/ad-unit/index.js
- src/customizer/control.js
- src/customizer/preview.js
- src/customizer/preview.scss
- src/frontend/style.scss
- webpack.config.js
> Release May 02

- includes/providers/gam/class-gam-model.php
- package-lock.json
- package.json
> Alpha release May 05

- includes/providers/gam/class-gam-scripts.php
- package-lock.json
- package.json
> Alpha release May 19

- CHANGELOG.md
- includes/providers/gam/class-gam-scripts.php
- newspack-ads.php
- package-lock.json
- package.json
> Release May 30

- composer.json
- composer.lock
- includes/class-core.php
- includes/class-placements.php
- includes/integrations/class-scaip.php
- includes/providers/gam/class-gam-model.php
- package-lock.json
- package.json
- tests/test-model.php
> Alpha release Jun 02

- CHANGELOG.md
- includes/providers/gam/class-gam-model.php
- newspack-ads.php
- package-lock.json
- package.json
- tests/test-model.php
> Alpha release Jun 03

- composer.lock
- includes/providers/broadstreet/class-broadstreet-provider.php
- package-lock.json
- package.json
- src/frontend/style.scss
> Alpha release Jul 14

- CHANGELOG.md
- composer.lock
- includes/providers/broadstreet/class-broadstreet-provider.php
- newspack-ads.php
- package-lock.json
- package.json
- src/frontend/style.scss
> Release Jul 25

- .prettierrc
- composer.json
- composer.lock
- includes/class-core.php
- includes/class-settings.php
- includes/integrations/class-ad-refresh-control.php
- includes/integrations/class-bidding-gam.php
- includes/providers/gam/class-gam-ad-block-recovery.php
- includes/providers/gam/class-gam-api.php
- includes/providers/gam/class-gam-lazy-load.php
- includes/providers/gam/class-gam-model.php
- includes/providers/gam/class-gam-scripts.php
- package-lock.json
- package.json
- src/blocks/ad-unit/editor.scss
- src/frontend/style.scss
- src/suppress-ads/index.js
- tests/bootstrap.php
> Alpha release Sep 26

- .prettierrc
- CHANGELOG.md
- composer.json
- composer.lock
- includes/class-core.php
- includes/class-settings.php
- includes/integrations/class-ad-refresh-control.php
- includes/integrations/class-bidding-gam.php
- includes/providers/gam/class-gam-ad-block-recovery.php
- includes/providers/gam/class-gam-api.php
- includes/providers/gam/class-gam-lazy-load.php
- includes/providers/gam/class-gam-model.php
- includes/providers/gam/class-gam-scripts.php
- newspack-ads.php
- package-lock.json
- package.json
- src/blocks/ad-unit/editor.scss
- src/frontend/style.scss
- src/suppress-ads/index.js
- tests/bootstrap.php
> Release Sep 27

- .circleci/config.yml
- CHANGELOG.md
- composer.json
- composer.lock
- includes/class-suppression.php
- includes/providers/gam/class-gam-model.php
- newspack-ads.php
- package-lock.json
- package.json
- tests/test-bidding.php
- tests/test-model.php
- tests/test-providers.php
> Release Oct 19

- composer.lock
- includes/providers/gam/api/class-ad-units.php
- includes/providers/gam/api/class-api.php
- includes/providers/gam/class-gam-model.php
- package-lock.json
- package.json
> Alpha release Nov 03

- .circleci/config.yml
- includes/providers/gam/api/class-api.php
- includes/providers/gam/class-gam-model.php
- package-lock.json
- package.json
- tests/test-model.php
> Alpha release Nov 08

- .circleci/config.yml
- includes/providers/gam/api/class-api.php
- includes/providers/gam/class-gam-model.php
- package-lock.json
- package.json
- tests/test-model.php
> fix(gam): validate API session

- .circleci/config.yml
- composer.lock
- package-lock.json
- package.json
> Alpha release Jan 13

- includes/providers/gam/class-gam-lazy-load.php
- includes/providers/gam/class-gam-scripts.php
_Follow steps in https://github.com/Automattic/newspack-plugin/pull/2238_
> Enable filtering of FE JS

- .circleci/config.yml
- composer.lock
- includes/providers/gam/class-gam-lazy-load.php
- includes/providers/gam/class-gam-scripts.php
- package-lock.json
- package.json
> Alpha release Jan 26

- composer.lock
- includes/class-core.php
- includes/class-fixed-height.php
- includes/class-placements.php
- includes/customizer/class-placement-customize-control.php
- includes/providers/broadstreet/class-broadstreet-provider.php
- includes/providers/gam/class-gam-model.php
- includes/providers/gam/class-gam-provider.php
- includes/providers/gam/class-gam-scripts.php
- package-lock.json
- package.json
- src/blocks/ad-unit/index.js
- src/customizer/control.js
- src/frontend/style.scss
- src/placements/placement-control.js
> Alpha release Feb 16

- CHANGELOG.md
- composer.lock
- includes/providers/gam/class-gam-lazy-load.php
- includes/providers/gam/class-gam-scripts.php
- newspack-ads.php
- package-lock.json
- package.json
> Release Feb 15

- composer.lock
- includes/class-core.php
- includes/class-fixed-height.php
- includes/class-placements.php
- includes/customizer/class-placement-customize-control.php
- includes/providers/broadstreet/class-broadstreet-provider.php
- includes/providers/gam/class-gam-model.php
- includes/providers/gam/class-gam-provider.php
- includes/providers/gam/class-gam-scripts.php
- package-lock.json
- package.json
- src/blocks/ad-unit/index.js
- src/customizer/control.js
- src/frontend/style.scss
- src/placements/placement-control.js
> Alpha release Feb 17

- CHANGELOG.md
- composer.lock
- includes/class-core.php
- includes/class-fixed-height.php
- includes/class-placements.php
- includes/customizer/class-placement-customize-control.php
- includes/providers/broadstreet/class-broadstreet-provider.php
- includes/providers/gam/class-gam-model.php
- includes/providers/gam/class-gam-provider.php
- includes/providers/gam/class-gam-scripts.php
- newspack-ads.php
- package-lock.json
- package.json
- src/blocks/ad-unit/index.js
- src/customizer/control.js
- src/frontend/style.scss
- src/placements/placement-control.js
> Release Feb 28

- composer.lock
- includes/providers/gam/api/class-api.php
- includes/providers/gam/class-gam-model.php
- package-lock.json
- package.json
> Alpha release Mar 02

- CHANGELOG.md
- composer.lock
- includes/providers/gam/api/class-api.php
- includes/providers/gam/class-gam-model.php
- newspack-ads.php
- package-lock.json
- package.json
> Release Mar 13

- .circleci/config.yml
- composer.lock
- includes/class-placements.php
- includes/providers/gam/class-gam-scripts.php
- package-lock.json
- package.json
> Alpha release Mar 16

- includes/providers/gam/api/class-api.php
- includes/providers/gam/class-gam-model.php
> fix(gam): handle account without networks

- composer.json
- composer.lock
- package-lock.json
- package.json
> Alpha release Mar 31

- .distignore
- CHANGELOG.md
- composer.lock
- includes/providers/gam/class-gam-model.php
- includes/providers/gam/class-gam-scripts.php
- newspack-ads.php
- package-lock.json
- package.json
> Alpha release Apr 28

- composer.json
- composer.lock
- includes/providers/gam/api/class-ad-units.php
- includes/providers/gam/api/class-advertisers.php
- includes/providers/gam/api/class-api.php
- includes/providers/gam/api/class-creatives.php
- includes/providers/gam/api/class-line-items.php
- includes/providers/gam/api/class-orders.php
- includes/providers/gam/api/class-targeting-keys.php
- package-lock.json
- package.json
> Alpha release Jul 20

- CHANGELOG.md
- composer.json
- composer.lock
- includes/providers/gam/api/class-ad-units.php
- includes/providers/gam/api/class-advertisers.php
- includes/providers/gam/api/class-api.php
- includes/providers/gam/api/class-creatives.php
- includes/providers/gam/api/class-line-items.php
- includes/providers/gam/api/class-orders.php
- includes/providers/gam/api/class-targeting-keys.php
- newspack-ads.php
- package-lock.json
- package.json
> Release Aug 07

- includes/providers/gam/api/class-ad-units.php
- includes/providers/gam/class-gam-scripts.php
- package-lock.json
- package.json
> Alpha release Aug 17

- CHANGELOG.md
- includes/providers/gam/api/class-ad-units.php
- includes/providers/gam/class-gam-scripts.php
- newspack-ads.php
- package-lock.json
- package.json
> Release Aug 24

- CHANGELOG.md
- composer.lock
- includes/providers/gam/api/class-api.php
- includes/providers/gam/class-gam-model.php
- newspack-ads.php
- package-lock.json
- package.json
> Release Sep 25

- includes/providers/gam/api/class-api.php
> fix(gam): silence network code check warning

- composer.lock
- includes/providers/gam/api/class-api.php
- newspack-ads.php
- package-lock.json
- package.json
> Alpha release Oct 16

- CHANGELOG.md
- composer.lock
- newspack-ads.php
- package-lock.json
- package.json
> Release Oct 31

- includes/providers/gam/api/class-targeting-keys.php
- includes/providers/gam/class-gam-model.php
Support custom targeting key-value "type" and "reportable type".
Also implements an action hook after GAM is setup.
Further details and testing instructions at https://github.com/Automattic/newspack-network/pull/13
> feat(gam): support custom type for targeting key-val

- .hooks/pre-push
- composer.json
- includes/class-core.php
- includes/providers/gam/api/class-targeting-keys.php
- includes/providers/gam/class-gam-model.php
- package-lock.json
- package.json
> Alpha release Nov 30

- .hooks/pre-push
- CHANGELOG.md
- composer.json
- composer.lock
- includes/class-core.php
- includes/integrations/class-bidding-gam.php
- includes/providers/gam/api/class-api.php
- includes/providers/gam/api/class-targeting-keys.php
- includes/providers/gam/class-gam-model.php
- newspack-ads.php
- package-lock.json
- package.json
> Release Dec 11

- composer.json
- composer.lock
- includes/class-bidding.php
- includes/class-custom-label.php
- includes/customizer/class-placement-customize-control.php
- includes/providers/gam/api/class-api.php
- newspack-ads.php
- phpcs.xml
- tests/bootstrap.php
- tests/test-providers.php
Updates PHPCS packages and the code.
1. No functional changes, smoke test to see if the changes to code look ok.
> chore: update PHPCS
