Automattic/newspack-ads

includes/class-newspack-ads-blocks.php, includes/class-newspack-ads-model.php, src/blocks/ad-unit/edit.js, src/blocks/ad-unit/view.php, tests/unit-tests/class-newspack-ads-tests-model.php
This PR is an expansion of the data model for Ads. This includes:
- Support for AMP and non-AMP fields
- Support for different Ad providers (Google Ad Manager, etc)
- Header code stored as an option.
The header code will also be injected into the HEAD in non-AMP requests. This is meant to be tested along with https://github.com/Automattic/newspack-plugin/pull/190. Complete testing instructions can be found there.
=> Extend Ad Unit Data Model

README.md, package-lock.json, package.json
This PR updates Calypso Build to enable the plugin to be build with current version of Node.js. Also updates the build scripts to match other Newspack Repos:
1) Make sure you are running current node, by  executing `nvm use stable`. `node --version` should show `v12.14.0`
2) Run `npm install`
3) Verify each of these scripts works as expected:
- `npm start`
- `npm run build`
- `npm run release:archive`
4) Verify the description of these scripts in the README is accurate.
=> Support for Node v.12, Cleaner Build Script Naming

includes/class-newspack-ads-blocks.php, includes/class-newspack-ads-model.php, phpcs.xml
This PR approaches the the problem of responsive ads by rendering containers for each defined size and using media queries to control visibility. 
In Newspack plugin's Ads UI it is possible to define multiple sizes for a single unit. We incorrectly assumed that this would cause the appropriate creative to be served based on viewport size, but this functionality doesn't come for free. 
[This doc](https://support.google.com/admanager/answer/7177589?hl=en) states:
> You can use CSS Media queries to define different ad sizes based on viewports
For non-AMP, [this doc](https://support.google.com/admanager/answer/3423562?hl=en&authuser=0) explains an approach to responsiveness using GPT `defineSizeMapping`. I wasn't enthusiastic about taking different approaches to AMP and non-AMP, so I opted to …
=> Responsive Ads

includes/class-newspack-ads-model.php
Use esc_html() instead of sanitize_title() for checking the saved ad unit code. Also use sanitize_title() instead of esc_attr() for a more valid CSS class on output.
To test:
1. In Newspack > Advertising enable Google Ad Manager
1. Click Configure
1. In the Global Code tab enter `000000000` in the "Google Ad Manager Network Code" setting
1. Go to the Individual Ad Units tab and add a new ad unit
1. Use `AT TopBanner` as the name
1. Use `AsiaTimes/Atimes_AMP/TopBanner` as the Ad unit code
1. Use `350` as width and `200` as height
1. Save the ad unit
1. Observe that the code has been changed to lowercase and slashes removed
1. Return to the Advertising Options screen
1. In the Global Settings, select the ad to appear in the "Global: Above Header" spot
1. View the home page, and observe the …
=> Allow for valid characters in the ad unit code

package-lock.json, package.json, src/blocks/ad-unit/editor.scss
Placeholders have been updated since Gutenberg 7.7 and the Ad Unit block looked broken with the new style.
This PR reverts the placeholder to its original style.
__How to test:__
1. Add Ad Unit block to a post -- See new style
2. Switch to this branch.
3. Refresh the editor
=> fix: placeholder box-shadow and background color since gutenberg 7.7

includes/class-newspack-ads-blocks.php, includes/class-newspack-ads-model.php
Several problems have popped up related to duplicate IDs for Ad Unit elements:
- In non-AMP requests the presence of duplicates leads to the units completely failing to fill, and rendering as blank white space.
- In other cases, duplicate units lead to conflicting media queries, which can break the responsive handling.
This PR resolves this by injecting a unique ID into element name for responsive Ad unit containers. Previously, non-responsive units already had a Unique ID, but responsive ones did not.
1. Try a variety of ad configurations, using Super Cool Ad Inserter, Newspack Ads block, and Newspack Plugin placements. Experiment with duplicate ad units.
2. Verify correct rendering and responsiveness.
=> fix: unique IDs for responsive ads

includes/class-newspack-ads-blocks.php
Closes #12 
In non-AMP mode, the ad block is a div. Since divs are full-width block elements, giving them `margin-left: auto; margin-right: auto` doesn't center them. This PR solves the issue by centering the child ad unit inside the div.
I chose to just use an inline script for this because Newspack Ads doesn't have a stylesheet, and the extra HTTP request would be a much bigger performance hit than an inline style on a fake stylesheet. If we ever need a stylesheet for this plugin we can refactor, but until then this should work well.
To test:
**1. Set up an ad unit. 
2. Take AMP off Standard mode or toggle it off for the current post.
3. Insert an Ad Block into a post or page. Select the center alignment for the block.
4. On frontend, observe the block is not centered.**
**5. Apply …
=> Fix ad centering in non-AMP mode

includes/class-newspack-ads-blocks.php
Part of https://github.com/Automattic/newspack-issues/issues/167
This PR adds support for adding targeting to ad units via a filter. Targeting is arbitrary key->val pairs when initializing an ad and can be used in GAM to fine-tune which creatives get delivered where.
In the future if other publishers want targeting, we can add UI for it to the ad management screens, but with little demand this should work fine.
To test:
1. Add the following code snippet somewhere:
```
add_filter( 'newspack_ads_ad_targeting', function( $targeting ) {
$targeting['foo'] = 'bar';
return $targeting;
} );
```
1 (alternate version). Get the custom plugin source [here](https://github.com/Automattic/newspack-issues/issues/167#issuecomment-622040752) and use the visual interface for adding targeting.
2. Examine the …
=> Add support for ad targeting via filter

includes/class-newspack-ads-blocks.php
This PR adds a filter for disabling the ad initial load. Disabling the ads initial load is required for header bidding, so that bids can be fetched before the ad is displayed. This filter shouldn't affect anything unless it's toggled off using a filter.
1. Add the following code snippet somewhere:
```
add_filter( 'newspack_ads_disable_gtag_initial_load', '__return_true' );
```
2. Visit a page with an ad. Observe no ad is displayed:
3. Open the browser JS console. Run `googletag.pubads().refresh()` in the console. Observe the ad(s) render:
4. Remove the code snippet. Ads should work normally as before.
=> Add filter for toggling initial ad load off/on

includes/suppress-ads.php
Related to https://github.com/Automattic/newspack-plugin/issues/571
This PR adds a filter for modifying whether ads should display. 
Testing instructions are at https://github.com/Automattic/newspack-plugin/pull/573.
On its own, this PR should not affect anything.
=> Add filter for controlling whether ads are displayed

includes/class-newspack-ads-blocks.php
This PR enables lazy loading for GAM ads in non-AMP mode.
I think lazy loading makes sense to do across all sites, since rendering ads that never get seen is not super great for a variety of reasons. In AMP mode lazy loading is automatic, since ads only render once they're in the viewport, so no further tweaks should be necessary for AMP.
These params are the ones BDN has been using for a while, so it seems like a sensible default starting point. We can tweak them further in the future if we get new info/data that says they should be tweaked.
To test:
1. Create a post with a custom HTML block at the top: `<div style="height:900vh"></div>` or add many screen lengths of lorem ipsum.
2. Add an ad block at the bottom.
3. View the post on the frontend. Using the browser's element inspector, …
=> Lazy load ads in non-AMP mode

includes/class-newspack-ads-blocks.php
The main purpose of this PR is to add a fix that will only define ad slots for ad containers that exist on the current page. This will prevent issues with and further optimize header bidding, ad delivery, etc. [That specific change is right here.](https://github.com/Automattic/newspack-ads/compare/fix/ad-slots?expand=1#diff-f00ee91a5e4c5891df399ba5eae186dcR198)
In order to make this change I had to do quite a bit of refactoring, because the special handling of responsive vs. regular ad units and the mixing of JS and PHP code made the codebase super difficult to work with. I've refactored the code in two ways:
1. Separate the PHP and JS from each other.
2. Within the JS section, simplify things to treat every ad slot the same way regardless of whether it's a responsive or regular slot. …
=> Don't define slots that aren't present, refactor non-AMP GAM script

includes/class-newspack-ads-model.php
This PR fixes some errors that were displayed in the Google Ad Manager console about unknown ad units. The issue was that there were duplicate script tags in the container markup and in the footer script for displaying an ad unit. 
#50 exposed the issue because after that change the container scripts were firing before the ad unit had been defined, but it appears there have always been two competing calls to `googletag.display` - one in the container markup and one in the footer script. This issue shouldn't have caused any problems on any sites, as re-displaying an already displayed ad does nothing.
1. Ad an ad unit to a page and visit it in non-AMP mode. In the JS console run `googletag.openConsole()`. Observe errors:
2. Apply this PR. Refresh the page. Observe that ads display and no …
=> Remove unnecessary, early ad display calls

includes/class-newspack-ads-blocks.php, src/blocks/ad-unit/view.php
Closes #51 
This PR adds easy, no-config-necessary handling for responsive ads. It does this by making each unique ad size a responsive breakpoint, so that each ad size will only show on screens equal-to-or-wider than the ad size. This should work nicely for the vast majority of ad units with no further work on the publisher's part.
For example, an ad unit with sizes `[728, 90]` and `[320, 50]` will show ads of both sizes on screens >= `728px` and only `320x50` ads on screens smaller than `728px`.
1. Configure an ad unit with multiple widths and add it to a post.
2. Visit the post with desktop screen size and confirm the large ad gets displayed (the small ad will also get sometimes displayed).
3. Shrink the screen size down. Refresh the page. Confirm only the small ad gets displayed. …
=> Automatic responsive ad handling for non-AMP mode.

includes/class-newspack-ads-blocks.php
This PR fixes an issue I noticed after #58 had already been merged. There was one edge-case I hadn't thought of: when the viewport is smaller than the smallest ad size. This PR makes it so that if an ad unit only has sizes available wider than the viewport width, that unit will not show any ads. Showing no ads is preferable to showing cut-off ads, which would impact ad viewability metrics.
1. Set up an ad with a size greater than 320px wide and add it to a post in an ad block:
2. Before applying this patch, view the post using a screen smaller than the ad width. Observe ad is cut off:
3. Apply patch. Refresh the page. Observe ad is simply not shown, and there isn't a big empty space where the ad would have gone:
4. Make the viewport bigger than the ad size. Refresh the page. Observe ad …
=> Dont show ads on viewports smaller than smallest ad size

.circleci/config.yml, .distignore, composer.json, composer.lock, package.json
1. Change release ZIP file structure, so that it matches the structure used by WPORG plugins
1. `semantic-release` config update which will enable [prereleases](https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#pre-release-branches). 
1. Run `npm run release:archive`
2. Install the plugin on a fresh site, confirm that it works as before
=> Build: change release zip structure

includes/class-newspack-ads-blocks.php, includes/class-newspack-ads-model.php
After #58 and #59, all non-AMP ads have automatic responsive ad handling using only one ad container. This removes the need for the multiple ad containers approach we were doing before. 
The multiple ad container approach where we show/hide the ad units using a media query works well in AMP, where there is no alternative to it. In non-AMP mode it is not the best-practices way of making responsive ads (and appears to be causing issues with BDN's ad targeting).
This PR removes the now unnecessary multiple containers for the global ads and makes them rely fully on the ad config.
1. Create an ad unit with multiple sizes.
2. Set it as a global ad.
3. View the ad on desktop screen size in non-AMP mode. You should see the small or the big ad.
4. Shrink the screen to mobile size. Refresh the …
=> Remove redundant responsive ad handling

includes/class-newspack-ads-blocks.php
The argument order has been updated in PHP, the old argument order is causing this warning to be logged:
```
PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /wordpress/plugins/newspack-ads/1.6.1/includes/class-newspack-ads-blocks.php on line 81
```
1. On `master`, see that the warning is logged
2. Switch to this branch, see that the warning is logged no more
3. Everything should work as expected
=> Update argument order in implode function

includes/class-newspack-ads-model.php
The `data-loading-strategy` attribute controls how eagerly (how many viewports) amp-ads load. See https://amp.dev/documentation/components/amp-ad/#data-loading-strategy-(optional)
This is important because if we load ads a user never scrolls to, these ads are never viewable and overall yield will suffer as a result. Unfortunately the default value is sub-optimal.
This article - https://medium.com/ampfuel/optimize-your-amp-pages-for-high-ad-viewability-rate-or-high-ads-served-311f6b539c73 - does a great job explaining the optimal value to use (and why). Fortunately the AMP runtime provides a constant we can use: `data-loading-strategy="prefer-viewability-over-views"`. This at the moment is 1.25 but may be fine tuned in the future if further testing reveals the need for a different number. …
=> Optimize amp-ads for viewability.

includes/class-newspack-ads-blocks.php, includes/class-newspack-ads-model.php
This PR adds some common ad targeting to all ad units. This enables sites to fine-tune their ad delivery in Google Ad Manager:
- It adds category targeting for singles and category archives. This will let people target ads to only deliver on certain categories.
- It adds post/page slug and ID targeting for singles. This will let people target ads to only deliver on certain posts/pages or on the homepage.
These sort of ads are generally more lucrative for publishers than sitewide ads, because publishers can charge a premium on them, and at least a couple of our publishers have been selling ads in this way already.
1. Configure and set a global ad unit.
2. With the network inspector open and **AMP enabled**, view a post in a category. Find the network request for the ad unit, scroll down to …
=> Add common ad targeting settings to ad units

src/blocks/ad-unit/index.js
Using Material's outlined instead of filled and add Newspack Blue colour to it.
The idea is to have our blue, just like Jetpack and WooCommerce do with respectively their green and purple.
=> Update block icon style and colour

.gitignore, package-lock.json, package.json, src/blocks/ad-unit/index.js, src/setup/newspack-logo.js
This PR installs npm package for wordpress/icons (and update calypso) and replaces the Material icons, and also updates the Newspack logo to the latest one.
1. run npm install
2. check if the new icon is being displayed properly
=> Add Gutenberg icon and replace Material

includes/class-newspack-ads-model.php
Closes #87 
This PR modifies the way we're generating responsive AMP ads to fix some issues when there are multiple ad sizes defined with the same width. See the example in #87 to better understand what I mean.
**Note**: I've removed the non-AMP parts out of `ad_elements_for_sizes`. Those bits were vestigial because they and aren't useful with the approach we've been using for non-AMP ads and that function never gets called in non-AMP mode.
(Ping me on Slack if you need specific GAM codes for these ads)
**1.** Use AMP Standard mode. Set up an ad with `300x250` and `300x50` sizes and assign it as a global header or footer ad:
**2.** On the frontend, observe the network request that the ad makes. In the size param, there should be two sizes. There should only be one `amp-ad` element:
**3.** …
=> Improved responsive AMP ad handling using multi-size

includes/class-newspack-ads-model.php
This PR addresses an issue where e.g. you set up an ad with sizes `300x250` and `300x600` and use that ad in a block or widget. Currently, only one of those ad sizes will ever be shown. Ideally, *either* of those two ad sizes would be shown. This PR implements this using the multi-size attribute, similar to #95, but much simpler because the ads don't have to be responsive. 
This should be fully backwards-compatible and shouldn't cause any issues on existing ad setups, except where someone may have set up an ad with multiple sizes and forgotten about it because only one size was ever shown. :) 
1. Set up an ad with sizes 300x250 and 300x600, or you can use an existing responsive ad you have laying around (like the leaderboards from #95)
2. Assign the ad as a widget. On the frontend, …
=> Add multisizes to non-responsive AMP ads.

includes/class-newspack-ads-model.php
After #98, sticky ads are able to show any size, so if you fill the sticky placement with an ad unit that has a large size, it can still possibly show the larger ads even though we're only showing the sticky ads at mobile viewports (< 600px).
This fix checks if the ad unit is being rendered in the sticky placement, and if so, overrides the ad unit dimensions so that it can't display any size larger than 600px. Any sizes smaller than 600px can still be shown according to normal multisize rules.
It's still possible for mobile viewports to render an ad size larger than the viewport, for instance if the ad size is 600x80 and the viewport is 375x812. But it's much easier now to ensure that desktop sizes are never served to mobile devices.
1. On `master`, create an ad unit that has at least …
=> fix: limit multisizes of sticky ads

includes/class-newspack-ads-model.php
I liked [your suggestion](https://github.com/Automattic/newspack-ads/pull/109#pullrequestreview-596930952) better than what I implemented, so I implemented and re-tested. Should show no difference in behavior compared to `master` now.
=> refactor: simplified approach for filtering out large sizes for sticky ads

package-lock.json, package.json, src/blocks/ad-unit/editor.scss, src/blocks/ad-unit/index.js
* Updates `@wordpress/base-styles` to latest version
* Changes style of placeholder to match Image block
* Adds support for wide and full-width
=> Update block placeholder and alignment options

includes/class-newspack-ads-model.php
It turns out that another plugin can [modify](https://github.com/INN/link-roundups/blob/be0f2a93a892904bf1d55a9dfd8ccf9311822d87/inc/link-roundups/class-link-roundups.php#L60) the `WP_Query` ran by this plugin!
1. Install the [Link Roundups plugin](https://github.com/INN/link-roundups/)
2. Create at least one link roundup
3. On `master` visit Newspack->Advertising wizard and observe the link roundups listed as ad units
4. Switch to this branch, observe the problem gone 🪄
=> Ensure only Ad Unit CPT are handled in query

.circleci/config.yml
Fixes a fatal caused when trying to activate a release package, because composer dependencies are not installed as part of the release build job.
To test, you need to create a build via CircleCI. I've already built https://github.com/Automattic/newspack-ads/releases/tag/v1.14.0-alpha.2 using this branch and confirmed that this build can be activated without a fatal, whereas attempting to activate https://github.com/Automattic/newspack-ads/releases/tag/v1.14.0-alpha.1 does result in a fatal.
=> fix: run composer install on release tasks

includes/class-newspack-ads-widget.php
These changes prevent PHP notices being logged when the widget renderer is called without an id, and when the widget updater is called without `stick_to_top` set. To test, insert the ads widget and confirm no PHP notices are logged and the widget displays as expected.
=> fix: handle undefined properties for widget

includes/class-newspack-ads-model.php
Due to the [limited precision of float values in PHP](https://www.php.net/manual/en/language.types.float.php), using a `===` comparison for ID values can sometimes fail even if the values appear to be the same to the naked eye.
For example, GAM ad unit IDs can sometimes be very large numbers like `21973793522`. When compared using `===` without casting the values as integers, PHP might cast one or the other value as a float instead, which means that `21973793522 === 21973793522` can actually be `false`.
This change explicitly casts both values as integers before making the comparison, avoiding this situation.
To test: 
1. You'll need an ad unit with ID that looks like a very large number like the above. The easiest way to do this is to [enable GAM …
=> fix: compare ad unit IDs as int rather than float

includes/class-newspack-ads-model.php, includes/class-newspack-ads-widget.php
This PR fixes an issue with the (soon-to-be-legacy) ads widget. If you save the widget without selecting any ad unit, it throws PHP warnings on the frontend. This is because in `Newspack_Ads_Model::get_ad_unit_for_display`, the call to `get_post( $id )` will return the current post when the default `$id` of `0` is passed in, and the current post has no ad meta data. I've hardened the logic to prevent this issue.
1. Before applying this patch, add an ads widget to the sidebar, don't select an ad unit, and Save:
2. On the frontend, observe the warnings thrown in the sidebar:
3. Apply this patch. Observe no warnings thrown in the sidebar:
=> Harden logic when no ad unit selected

includes/class-newspack-ads-model.php
Create >100 ad units, or trust [the docs](https://developer.wordpress.org/reference/classes/wp_query/#pagination-parameters) ;) :
> Use 'posts_per_page'=>-1 to show all posts (the 'offset' parameter is ignored with a -1 value).
Closes #106
=> fix: return all ad units

includes/class-newspack-ads-model.php
As reported by @kmwilkerson, GAM limits targeting values to 40 characters so longer slugs will only be targetable within GAM using the first 40 characters. To avoid confusion for publishers, this PR removes `slug` as a targetable field and adds `post_type` for broader targetable coverage.
Closes #164.
1. Make sure you have a global ad unit visible on a singular post page
2. With the network inspector open, visit a singular post and see make sure `category`, `post_type` and `ID` are being sent through the `scp` (with AMP enabled), or `prev_scp` (with AMP disabled) query parameter in the ad request.
=> Fix(targeting): remove post slug and add post type

includes/class-newspack-ads-model.php
Allows the advertising wizard to accept multiple GAM network codes as a comma-delimited string, as specified by MCM, and renders those codes in the slot attribute for both AMP and non-AMP ad units. Note that it's currently not possible to fully test MCM in a non-production environment.
Also fixes a minor bug in the Advertising wizard where saving a new value to the Network Code field and then navigating to a different view within the React app resets the field back to the previous value.
Closes #157.
1. Check out this branch as well as https://github.com/Automattic/newspack-plugin/pull/1123 (make sure to rebuild with `npm run build`).
2. In WP Admin, go to **Newspack > Advertising**. Turn on Google Ad Manager if not already enabled, then click "Configure."
3. In the **Network Codes** …
=> feat: allow multiple comma-delmiited GAM network codes

includes/class-newspack-ads-model.php
Partial revert of #168 - it has been reported that the `slug` is used by some.
=> feat(targeting): add slug back

includes/class-newspack-ads-gam.php, includes/class-newspack-ads-model.php
Automatically creates custom keys for [targeting key-values](https://support.google.com/admanager/answer/188092?hl=en). The created keys are `ID`, `category`, and `post_type` of type `FREEFORM` if they are not found `ACTIVE` in GAM.
Closes #165.
1. Visit your GAM dashboard at **Inventory -> Key-values** and make sure the keys mentioned above **don't exist**
2. Checkout this PR and make sure your setup is connected to GAM
3. Visit the Advertising wizard page (the custom keys should be checked and updated here, if necessary)
4. Visit your GAM dashboard and make sure the keys exists at **Inventory -> Key-values**
=> feat(gam): create target key-values on sync

includes/class-newspack-ads-gam.php, includes/class-newspack-ads-model.php
Allow the user to upload Service Account credentials to provide a connection with GAM.
This is an improvement over the current approach implemented by https://github.com/Automattic/newspack-ads/pull/163, which uses a JSON file provided by Google containing credential secrets to connect with GAM. Instead of uploading the file to  `WP_CONTENT_DIR`, we will store the credentials as WordPress options.
1. Repeat the steps from https://github.com/Automattic/newspack-ads/pull/163 to create your Service Account and generate your credentials file
2. Checkout this branch and https://github.com/Automattic/newspack-plugin/pull/1149
3. Visit Newspack Ads dashboard and notice the error shown on the Google Ad Manager card
4. Click "Configure" and observe the notice warning legacy mode
5. Click on the …
=> feat(gam): service account credential options

includes/class-newspack-ads-gam.php, includes/class-newspack-ads-model.php, tests/test-model.php
Implements and closes #183
As suggested by the issue, the Ad Units editor will never be blocked, instead, the network code related to the credential "replaces" the saved network code. If the credentials are removed, the previous network code will be restored.
This change affects every method that uses `get_active_network_code()`, which includes ad units configuration methods.
This PR also introduces the `is_sdk_compatible()` method, which disables GAM connection and flags `incompatible` in the case Constant Contact Form plugin is enabled. 
1. Repeat the steps from https://github.com/Automattic/newspack-ads/pull/163 to create your Service Account and generate your credentials file
2. On a new installation, checkout https://github.com/Automattic/newspack-plugin/pull/1151, visit Newspack Ads …
=> Handle legacy network code and incompatible plugin

includes/class-newspack-ads-gam.php
Addresses post-merge concerns brought at https://github.com/Automattic/newspack-ads/pull/184 
Activate Constant Contact Form plugin, visit Newspack Ads dashboard and see the new message shown on the Google Ad Manager card.
=> chore: update env compatible method

includes/class-newspack-ads-model.php
GAM API has a rate limit of 8 requests per second, this PR implements a class variable to store fetched ad units to prevent excessive consecutive API calls.
Make sure ad units are properly loaded and displayed on the Ads GAM wizard and Ad Unit widget configuration. Nothing should change.
=> perf: cache ad units

includes/class-newspack-ads-blocks.php, includes/class-newspack-ads-settings.php, includes/class-newspack-ads.php, tests/test-settings.php
Implements configurable settings for the Ads plugin. Initially set up to modify lazy load settings, but with support for multiple cases.
The default values for lazy load settings also changed and are as suggested by @kmwilkerson. It should produce the following immediate change on GPT configuration script:
```diff
googletag.pubads().enableLazyLoad( {
-  fetchMarginPercent: 500,   // Fetch slots within 5 viewports.
+  fetchMarginPercent: 100,   // Fetch slots within 1 viewport.
-  renderMarginPercent: 200,  // Render slots within 2 viewports.
+  renderMarginPercent: 0,  // Render slots upon view.
mobileScaling: 2.0         // Double the above values on mobile.
} );
```
A setting is an array with the following keys:
- description: The description of the setting.
- help: The help text for …
=> feat: customizable settings

includes/class-newspack-ads-gam.php, includes/class-newspack-ads-model.php
Reinstates Service Account connection management (removed in ad5a5ac4dc6c59602f9b71f4ea78c337e3c55507), if OAuth is unavailable.
If both OAuth and Service Account connections are set up, the former will be preferred. 
See https://github.com/Automattic/newspack-plugin/discussions/1190
=> feat(gam): service account credentials managing

includes/class-newspack-ads-settings.php
Removes the `/settings-list` API endpoint and use the `get_settings_list()` method for the `/settings` endpoint.
Addresses [review from a previous PR](https://github.com/Automattic/newspack-ads/pull/213#pullrequestreview-801050820).
=> refactor: remove `/settings-list` endpoint

.circleci/config.yml, includes/class-newspack-ads-scaip.php, includes/class-newspack-ads-settings.php, includes/class-newspack-ads.php
This PR adds SCAIP settings as a section on Ads settings.
I'd appreciate a second opinion from the reviewer if we should also remove the original SCAIP settings page. This is not implemented here and I'm not sure if we should.
Closes #177.
1. Check out this branch and https://github.com/Automattic/newspack-plugin/pull/1248 for a section layout fix
2. Make sure you have SCAIP installed and have tweaked its default settings
3. Visit the Advertising -> Global Settings wizard
4. Observe your settings are being shown at the "Post ad inserter settings"
5. Update the settings, visit the SCAIP settings page and confirm the results match
=> feat: integrate SCAIP settings

.circleci/config.yml, includes/class-newspack-ads-gam.php, includes/class-newspack-ads-model.php
A pesky GAM issue.
1. Visit your GAM instance and uncheck "API access" (`https://admanager.google.com/<network-code>#admin/settings/network`)
2. On `master`, observe that no GAM ad units are loaded
3. Switch to this branch, observe an error displayed with the link to the settings
=> feat: handle missing API access error

includes/class-newspack-ads-gam.php
Fixes a bug:
1. On `master`, visit the Advertising wizard on a site in legacy mode (without GAM connection)
2. Observe there's not notice about legacy mode and no GAM network input
3. Switch to this branch, observe there are the notice and input
=> fix: connection mode

includes/class-newspack-ads-gam.php, includes/class-newspack-ads-model.php
Handles a user connection that has multiple GAM accounts and the ability to choose which should be used by Newspack Ads.
Closes #225 
1. Check out this branch and https://github.com/Automattic/newspack-plugin/pull/1334
2. Make sure you are authenticated with Google OAuth (Connections wizard) and your account has at least 2 connected GAM networks.
3. Visit the Advertising wizard and click "Configure" on the Google Ad Manager card.
4. Confirm the new dropdown selector to choose between the available networks
5. Select a different network and make sure the ad units are updated accordingly
6. Refresh the page and confirm your selection persisted
7. Visit the Placements area and confirm you are able to use the ad units for the selected network
=> feat: handle multiple gam accounts

includes/class-newspack-ads-bidding.php, package-lock.json, package.json, src/prebid/index.js, webpack.config.js
The current implementation of the `prebid.js` script does not allow it to be loaded asynchronously. It requires an [extra webpack plugin](https://github.com/prebid/Prebid.js/blob/master/plugins/pbjsGlobals.js) on its build so it can correctly pull previously queued commands and inject itself to the window.
This PR implements the plugin, add the `async` attribute to the script and updates the prebid.js version
Run `npm ci && npm run build` and make sure `DevTools` continue to display the logs as specified at #231.
=> fix: allow prebid.js to load async

includes/class-newspack-ads-bidding.php
Hide header bidding settings if using AMP.
1. Remove `NEWSPACK_AMP_PLUS_ENABLED` if you have it and make sure AMP is enabled
2. Make sure you have `NEWSPACK_ADS_EXPERIMENTAL_MEDIANET` set to true
3. On the master branch, visit Newsletters -> Settings
4. Observe the header bidding settings are visible, although it wouldn't work because of JS requirements
5. Switch to this branch and refresh the page
6. Confirm header bidding settings are no longer visible
7. Visit the Placements, edit a placement and confirm the bidder placement ID is also not displayed
=> fix: hide header bidding if using AMP

includes/class-newspack-ads-placements.php, includes/class-newspack-ads-sidebar-placements.php
Implements "stick to top" support for any registered placement configured with `'supports' => [ 'stick_to_top' ]`. Enables support for the "Sidebar 1" placement.
Closes #244 
- Check out this branch and https://github.com/Automattic/newspack-plugin/pull/1365
- Confirm you have AMP Plus enabled
- Visit **Advertising -> Placements** wizard, enable and edit the **Sidebar** placement
- Select a viable ad unit as "after widget area", check the "Stick to top" checkbox and save
- Visit a page/post with the sidebar and confirm the ad sticks to the top on scroll
- Disable AMP Plus, refresh the page and confirm the ad is **no longer sticking**
- Visit the wizard page again, edit the previous placement and confirm the "Stick to top" option is no longer available
=> feat(placements): stick to top support

includes/class-newspack-ads-placements.php, includes/class-newspack-ads-sidebar-placements.php
By default, the sidebar placements expect a sidebar to have widgets in order to display the placement ad. This is an acceptable assumption for most cases, but there are 3 Newspack sidebars that can benefit allowing to display an ad without having to configure widgets:
- Above article
- Below article
- Above copyright
This PR implements this behavior and also sets them to be a "single unit" placement, which means it won't have "before widgets" and "after widgets" ad units.
- Check out this branch
- At Advertising -> Placements, set an ad unit for each of the mentioned sidebars above
- Make sure you don't have any widgets configured on these sidebars (Appearance -> Widgets)
- Visit a post and confirm the ads are visible for all placements
=> feat: allow empty sidebars for article and above copyright

composer.json, composer.lock, includes/class-newspack-ads-gam.php
Update Google Ads library from the deprecated v202102 to the latest v202111.
Closes #267 
Check out this branch and test common GAM tasks:
1. Connect using a service account (JSON file)
2. Create a new ad unit
3. Edit a created ad unit
4. Delete an ad unit
5. Visit a page with ads and confirm they are visible
=> chore(deps): googleads-php-lib from v202102 to v202111

includes/class-newspack-ads-bidding.php
Avoid double fetching when using header bidding by disabling initial load for GTag.
c21f1a2298c68e3a14fd07c88841a81a4c79c0fb initially proposed the use of the `newspack_ads_disable_gtag_initial_load` filter to determine the use of `disableInitialLoad()`. This is problematic because our `prebid_script()` method have particular variables that prevents it from being unnecessarily printed on the page. Not printing it means ads wouldn't load (unless a third-party calls for the `refresh()` method).
82ebc8718903856d2ac344d2cb10c763702c8b96 updates to call `disableInitialLoad()` directly on the `prebid_script()` method, which is a better practice in regard to how GPT and Prebid configuration scripts should interact.
- While on the master branch ensure you have experimental header bidding …
=> fix(header-bidding): disable initial load for gtag

.circleci/config.yml
Updates `post_release` job to match the latest Git workflow changes.
=> chore: update post-release job to pull changelog and semver changes

includes/class-newspack-ads-placements.php
Ensure the active placement have ID for the `get_placements_data_by_id()` method. The odd case of a placement ad unit being left blank after being filled can cause inconsistent placement data.
1. On the master branch select an ad unit for a global placement and save
2. Select blank (Select an Ad Unit) for the same placement
3. Visit a page where this placement should be displayed
4. Debug logs should display: `Notice: Undefined index: id in newspack-ads/includes/class-newspack-ads-placements.php on line 366`
5. Check out this branch, refresh the page and no notices should be thrown.
=> fix(placements): ensure active placement have ID

includes/class-newspack-ads-custom-label.php, includes/class-newspack-ads-settings.php, includes/class-newspack-ads.php
Adds support for a custom label to be displayed right before a placement ad renders.
Closes #193 
1. Check out this branch and make sure you have global placements configured with valid ad units
2. Navigate on the site and confirm nothing changes with the ad rendering
3. Visit **Advertising -> Settings** and enable the **Custom ad label** setting
4. Visit your website and confirm the default label is being applied to rendered ads
5. Change the default label to something else and confirm the label changes on the frontend as well
6. Modify a placement to an ad unit without a valid creative and confirm the ad and label are not rendered
7. Test the label visibility with and without AMP
8. Change your website's primary body font to any other to confirm the style is appropriate
=> feat: custom ad label

includes/class-newspack-ads-custom-label.php
Changes the custom ad label default value from "Advertising" to "Advertisement".
=> fix: ad label default value

CHANGELOG.md, includes/class-newspack-ads-gam.php, newspack-ads.php, package-lock.json, package.json
There is a logic error on how some of the `get_serialised_*` methods work. If the result of the query returns empty, it will always fall to return all of the entities.
This hotfix changes the default argument value to `null` so it returns an empty array as expected for empty results.
=> hotfix: gam serialised method arg

CHANGELOG.md, includes/class-newspack-ads-bidding.php, newspack-ads.php, package-lock.json, package.json
The header bidding ad unit sizes should be reindexed after being filtered by `array_intersect()`. Otherwise, `wp_json_encode()` will generate an object keyed by the existing indexes instead of an array.
1. On the master branch, create an ad unit with a couple of standard sizes and a non-standard one: `100x50`, `728x90`, `970x250`
2. Place this ad unit on a placement with a random Media.net placement ID
3. Visit the page, open DevTools and with the element inspector, search for: "mediaTypes"
4. Observe the `sizes` are an object keyed by its indexes
5. Switch to this branch, refresh the page and confirm the value of `sizes` is an array.
=> hotfix: reindex filtered sizes

includes/class-newspack-ads-gam.php, includes/class-newspack-ads-model.php
Add the `template` targeting key using [`get_page_template_slug()`](https://developer.wordpress.org/reference/functions/get_page_template_slug/) for more targeting coverage.
It should cover the targeting of wider creatives for #295 (https://github.com/Automattic/newspack-theme/pull/1699).
1. Check out this branch and visit Advertising wizard
2. Notice the success message inside the GAM card confirming the creation of the new targeting key. (The wizard will always look for missing useful targeting keys on load and create them)
3. Create a post using the One-column template, visit the page and confirm the targeting is being configured by inspecting the searching for : `"template":`. You should find the `gpt` config like this:
=> feat: add template targeting key

includes/class-newspack-ads-gam.php
Closes #250 
1. Make sure you are connected with a GAM network
2. Visit the **Advertising -> Google Ad Manager -> Configure** page and your Ad Units dashboard at GAM
3. Make sure you have `inactive` ad units on your GAM dashboard
4. Confirm that on this branch they are no longer visible
=> fix: dont query inactive ad units

CHANGELOG.md, includes/class-newspack-ads-gam.php, newspack-ads.php, package-lock.json, package.json
GAM targeting key names are case-insensitive and should be treated as such. The current query uses a case-sensitive operator which fails to find existing different-case keys and causes a creation error by attempting to create duplicates.
This PR changes the query to search using the [case-insensitive `LIKE` operator](https://developers.google.com/google-ads/api/docs/query/case-sensitivity). It also fixes a logic error on the usage of `strpos()`, which returns `false` if the needle is not found, not an `int`.
Since GAM doesn't delete entities, if you click to "delete" any of the default targeting keys and recreate with uppercase characters, it will actually re-enable the archived key with the previous lowercase characters.
To test with a new key, create a key called `Uppercasetest` on your …
=> hotfix: gam targeting keys names are case-insensitive

src/wizard-settings/header-bidding-gam/index.js
React does not like having `div`s in `p`s:
=> chore: DOM nesting in a React component

includes/bidders/class-newspack-ads-bidder-openx.php
Enables user syncing through iframes when OpenX is active.
According to [Prebid.js documentation](https://docs.prebid.org/dev-docs/bidders/openx.html):
> By default, Prebid.js version 0.34.0+ turns off user syncing through iframes. OpenX strongly recommends enabling user syncing through iframes. This functionality improves DSP user match rates and increases the OpenX bid rate and bid price. Be sure to call pbjs.setConfig() only once.
1. Make sure you have:
1. AMP Plus on
2. GAM successfully connected
3. Header bidding enabled through: `define( 'NEWSPACK_ADS_EXPERIMENTAL_BIDDERS', true );`
2. Check out this branch and at Newspack Ads -> Settings, make sure you have OpenX as an active bidder and a random OpenX Platform ID
3. Visit a page with ads placed and using DevTools search the DOM for …
=> feat(header-bidding): enable user syncing through iframes for OpenX

includes/class-newspack-ads-blocks.php, includes/class-newspack-ads-model.php, includes/class-newspack-ads-scaip.php, includes/class-newspack-ads-sidebar-placements.php
Removes the use of a custom filter to determine if the ad unit should be rendered using the responsive strategy for AMP ads. Instead, use the number of sizes and if it's a fluid ad unit.
Also refactors how the GPT script is rendered, some method names for improved readability, and bug fixes for the AMP responsive strategy.
1. Check out this branch and make sure you have AMP active and AMP Plus **disabled**
2. Place ad units with a singular size in a global placement, a block, and a widget
3. Confirm the ads renders as expected
4. Place multi-sized ad units in a global placement, a block, and a widget
5. Change your viewport to confirm it's using the responsive strategy
=> fix: use ad unit size count for determining responsive amp ads strategy

includes/class-newspack-ads-bidding.php, includes/providers/gam/class-newspack-ads-gam.php
While attempting to create a header bidding GAM order without having any enabled bidder, it attempts to create without creative placeholders. This is because the creative placeholders are generated combining the accepted ad sizes from enabled bidders. This PR modifies the `get_all_sizes()` method to always return the default accepted ad sizes if no bidder sizes are found.
1. On a fresh instance, connect to GAM and enable header bidding through `define( 'NEWSPACK_ADS_EXPERIMENTAL_BIDDERS', true );`
2. While on master attempt to create a GAM order without having any bidder selected as enabled
3. Confirm the "required creative placeholder" error
4. Install this branch and confirm you are able to create the order without selecting a bidder
=> fix(header-bidding): ensure sizes for creative placeholders

CHANGELOG.md, newspack-ads.php, package-lock.json, package.json
Pulls changes in from `release` after the [last post-release job failed](https://app.circleci.com/pipelines/github/Automattic/newspack-ads/938/workflows/5f33484f-34b3-49cd-acec-8c3553f22dd0/jobs/2626).
=> fix: bad post-release merge

includes/class-newspack-ads-bidding.php
By clearing a placement of its bidder unit IDs, the stored value is an empty string. This empty string should be checked before creating the Prebid script configuration
1. Make sure you have AMP off (or AMP Plus on), GAM connected and header bidding configured through `define( 'NEWSPACK_ADS_EXPERIMENTAL_BIDDERS', true );`
2. While on master, make sure you have enabled bidders and debug mode on Newspack Ads -> Settings
3. Edit a placement with a random ID for the bidder, then edit again to clear the ID
4. Visit the page where the ad is rendered and confirm on the page logs that there's a bid attempt
5. Check out this branch, refresh the page and confirm there's no bid attempt
6. Add a random bidder ID for the placement again, visit the page to confirm that the bid continues to work as …
=> fix: prevent empty bidder unit id

includes/class-newspack-ads-blocks.php, includes/class-newspack-ads-model.php, tests/test-model.php
There currently are 2 different strategies to handle size mapping and responsive ads. Although we need both strategies to meet AMP and GPT requirements, the applied rules should be the same to avoid unexpected behavior.
This PR unifies the size mapping logic by implementing the `get_responsive_size_map()` method and simplifies how it's applied to both GPT and AMP.
There shouldn't be any noticeable change:
1. Check out this branch and make sure ad units with multiple sizes are displayed as expected for different viewports with AMP and AMP Plus
3. Written test should pass
=> refactor: unify responsive size map

.github/dependabot.yml, package-lock.json, package.json
While debugging a `newspack-scripts` related issue, I've noticed that dependabot is not configured for this repository. It should be, as on the other repositories.
=> add dependabot and update newspack-scripts

includes/providers/gam/class-gam-model.php, includes/providers/gam/class-gam-provider.php
The GAM ad unit code for AMP is currently verifying the size count to use the responsive strategy. This generates unnecessary calculation and additional markup for slots that only results in 1 viewport after the size map calculation.
This PR moves the size map calculation to the `get_ad_unit_amp_code()` method so it verifies the viewport count before deciding which strategy to use. It also makes the size map calculation more accurate, considering the filtered `$size` array for the sticky placement.
This change also fixes an issue where an AMP sticky ad would not properly render due to the additional markup generated by the responsive strategy, in case the ad unit is multi-sized.
It also refactors the `<amp-sticky-ad />` generation for better maintenance.
1. Make sure you have AMP Plus …
=> fix(gam): consider size map viewport count for responsive strategy

includes/class-placements.php
The suggested "default" ad units for the standard global placements are not being used and cause these placements to always render an empty div. This gets fixed if the user disables the placement or manually set a different value followed by an empty value.
This PR removes those default ad units since there's no current reason to keep them.
1. While on master make sure you don't have the `_newspack_ads_placement_global_below_header` option. It will make the placements system use the `default_ad_unit`
2. Visit a page and confirm there's a `1.5rem` gap between the header and the content and there's an empty `<div class="newspack_global_ad global_below_header" />`
3. Check out this branch, refresh and confirm the gap and the `<div />` are gone
=> fix(placements): remove default ad unit

includes/providers/gam/class-gam-scripts.php
After #329 the size mapping part of the GPT script was simplified but some code from the previous approach remained. This PR removes the unused code and moves the comments to PHP to reduce printed bytes.
No changes should take place, AMP Plus and off-AMP ads should continue to render without errors.
c61185245ce40b57e0bb4b68ebeea66235b696cd (with improvements on 8ab8e5333f77753b5cc54c5d84f56e830b8c17cc) also isolates the common targeting key-val across ad units, which should, for most cases, be the entire targeting. This also aims to reduce printed bytes by not repeating the same targeting parameters for every ad unit on the page.
=> fix(gam): remove unused gpt script

includes/integrations/class-ad-refresh-control.php
Ensure returned values from the Ad Refresh Control integration API are the same as stored.
1. While on master and https://github.com/Automattic/newspack-plugin/pull/1587, visit the Add-Ons page on the Ads wizard and make sure you have Ad Refresh Control toggled on
2. Visit the Settings wizard and enter non-numeric values to the "Excluded Advertiser IDs" input
3. Save and confirm the values persisted
4. Refresh and confirm the invalid values were not stored
5. Check out this branch, repeat step 2 and confirm the values were cleared on save
Although I believe this is not a user-friendly way of handling invalid user input, it is the same way the plugin currently handles it on its own Settings page. I don't think we should implement this type of enhancement for this integration but am open to …
=> fix(integrations): ad refresh control sanitized settings

includes/providers/gam/class-gam-scripts.php
Some publishers push custom GPT scripts through plugins that either apply the script or that allow custom manual scripts to be printed on the page.
This change ensures that the `googletag.cmd` array is initialized as soon as possible on the page and prevents `googletag is not defined` errors.
No changes should take place, with AMP Plus on make sure ads are still properly rendered on the page.
=> chore: move gpt initialization

includes/integrations/class-ad-refresh-control.php
Add `0` to the list of disabled advertisers for refresh control.
Closes #370
1. Check out this branch, visit the Add-Ons page and make sure you have Ad Refresh Control enabled
2. Visit the Settings wizard and confirm you have no **Excluded Advertiser IDs**
3. Visit the front page, inspect the HTML and search for `advertiserIds`
4. Confirm the value is `[1]`. The values are sent as a PHP to JSON encoded map, so index `0` being of value `1` means disable `0`
5. Fill `1234` to the **Excluded Advertiser IDs** field and save
6. Confirm the value printed on the page is now `{ "1234": 1, "0": 1 }`
=> feat(integrations): disable refresh control for adsense

includes/class-bidding.php, includes/class-core.php, includes/class-placements.php, includes/class-providers.php, includes/utils.php, src/frontend/style.scss, tests/class-newspack-ads-test-provider.php, tests/test-providers.php
Implements the ad unit mock preview when viewing ad units through the customizer.  It also:
- [Fix placement hook data to use the default provider if not yet stored](https://github.com/Automattic/newspack-ads/pull/367/files#diff-fb1912afb032a05d595f377bddbe82f63efb460f9df64caee448b35835d07b8aR261-R266)
- Extends the Providers class API
- Inaugurates `utils.php` for shared utility across the plugin
Closes #334 and is also an important part of the work in progress at #287.
1. Check out this branch, run `npm run build` and confirm you have ad units applied to placements
2. Visit a page with ads and enter the Customizer
3. Confirm you see the same ad unit mock preview like the one displayed in the block editor
Updated test for the extended Providers class API should also pass.
=> feat(placements): ad unit preview

includes/providers/gam/class-gam-model.php, includes/providers/gam/class-gam-scripts.php, tests/test-model.php
Implements size map filters and a width threshold to allow tablet ads to share rotation with desktop ads regardless of their width ratio difference.
Closes #364 
1. Create an ad unit with the following sizes: `320x180`, `320x480`, `640x360`, `960x540` and apply this ad unit to a global placement
2. With AMP Plus on, visit the page and inspect the generated GPT script (search for `all_ad_units`)
3. Confirm that the script contains the following `size_map` config parameter formed for the created ad unit:
```json
{
320: [
[320, 180],
[320, 480],
],
640: [
[640, 360],
],
960: [
[640, 360],
[960, 540],
],
}
```
On master, the viewport `960` doesn't include the `640x360` size.
4. Toggle AMP Plus off and refresh the page
5. Inspect the `<amp-ad />` element and confirm the grouping of tags also …
=> feat(gam): size map filters and width threshold

includes/providers/gam/class-gam-scripts.php, src/frontend/style.scss
Prevents the rendering of slot creatives larger than the container offset width. Also puts it behind a filter so publishers can modify its behavior per ad unit.
It also proposes a bleed of 40px by default, so the centered creative can extrapolate at most 20 pixels on each side.
~~The `newspack_ad_global` was added a default `width: 100%;` to ensure that the container fills the available space. This shouldn't be an issue for regular units, only for the full-width template, which requires this PR: https://github.com/Automattic/newspack-theme/pull/1766~~
~~I'd also appreciate a confidence check on the use of the direct parent `offsetWidth` for this strategy. An alternative is to resolve the issue by case, for example, detect if the slot is within `entry-content`, use its width as the …
=> feat(gam): strict container bounds for ad slot

includes/class-providers.php
A small performance tweak for fetched providers' data.
Moves the cache to the `get_provider_data()` method level in order to increase its coverage across different methods.
No changes should take place.
With GAM connected and Broadstreet installed and connected visit the Placements editor and confirm data from both providers are available for editing.
Provider methods tests passing should also confirm the expected data is being returned.
=> perf(providers): optimize data cache

includes/class-bidding.php, includes/providers/gam/class-gam-model.php
As per #367, these size transformation methods are now part of the `utils.php` file and are not used.
cc92f7d5f019185eafd15716c5fbc7a987452e42 also applies the util function to the multisize attribute for GAM AMP ad code generation.
=> chore: remove unused methods

includes/class-blocks.php, package-lock.json, package.json, src/blocks/ad-unit/edit.js, src/blocks/ad-unit/index.js
The Ad Unit blocks require to have a placement ID that does not have to persist or be predictable due to the dynamic nature of such placements.
This PR simplifies the ID implementation by just using php's `uniqid()` on placement registration instead of the current complex ID generation on block editing.
Closes #363 
Check out this branch, create multiple ad unit blocks on the same page and confirm they all render as expected.
=> fix(blocks): simplify block placement id

includes/class-suppression.php
Allow the Newspack Ads Settings block editor panel to be displayed on any post type considered "[viewable](https://developer.wordpress.org/reference/functions/is_post_type_viewable/)".
1. On the master branch, edit a public custom post type that uses the block editor (a Newspack listing, for example)
2. Observe the "Newspack Ads Settings" is not displayed
3. Check out this branch, refresh and observe the panel
4. Toggle the Ad Suppression **on** and save
5. Visit the page and confirm no ads are displayed
=> feat: enable suppression for any viewable post type

CHANGELOG.md, includes/providers/gam/class-gam-scripts.php, newspack-ads.php, package-lock.json, package.json
The common targeting parameters are encoded to JSON using the `JSON_FORCE_OBJECT` flag. This was initially applied so that an empty result would still encode to `{}`. The unintended result is that it is forcing objects to every nested array, creating `{ "0": "value" }` instead of the expected `[ "value" ]`.
There's no need to ensure that an empty result renders a `{}`, just removing the flag suffices.
1. With the latest release, apply 2 categories to a single post. Visit the page with the extra `?googfc` parameter
2. Inspect the rendered ads and confirm the targeted category is `[object Object]`
3. Check out this branch, refresh the page and confirm the categories are listed correctly
=> fix(gam): common targeting array

CHANGELOG.md, includes/customizer/class-customizer.php, newspack-ads.php, package-lock.json, package.json
Lodash is not compiled to the final script so it must be enqueued as a dependency of the `customizer-control.js` script.
Since the introduction of the block-based widget editor, lodash is enqueued by default to the customizer. To test this PR you must disable it by installing the [Classic Widgets](https://wordpress.org/plugins/classic-widgets/) plugin.
On the release branch, visit the customizer and confirm the `undefined` lodash error. Check out this branch, refresh and confirm the error is gone and you are able to edit and save Ad Placements.
=> fix(customizer): enqueue lodash dependency

includes/providers/gam/class-gam-model.php, includes/providers/gam/class-gam-scripts.php
Add targeting support for tags and authors over GAM.
Closes #395 
1. Check out this branch and visit a post with multiple tags using the `?googfc` parameter
2. Make sure you have Co-Author Plus **disabled**, Inspect the targeting options, and observe the author and tags targeted
3. Enable Co-Author Plus, add a co-author to the post and confirm using the inspector that the authors' slugs are targeted
=> feat(gam): targeting for tags and authors

includes/providers/gam/class-gam-scripts.php
#375 introduced "bounds containers", which restricts the sizes for GPT ads inside `.entry-content` and `.widget-area`.
The elements that contain an ad unit can be expanded to also include `.wp-block-column`, which is the common class for a column inside the Columns block.
| Master | This branch |
| --- | --- |
| <img width="1304" alt="image" src="https://user-images.githubusercontent.com/820752/167480577-e4158c76-77a9-4ce1-bc30-c360da3ffb2b.png"> | <img width="1252" alt="image" src="https://user-images.githubusercontent.com/820752/167480664-98088e53-c861-4e01-a239-d1b7619c6e5a.png"> |
Closes #400
1. In the master branch, add an ad unit with `300x250` and `728x90` sizes to a block column with a maximum width of 600.
2. Visit the page and confirm the 728x90 creative is rendered on the page …
=> feat(gam): block column as a bounds container

CHANGELOG.md, includes/class-core.php, newspack-ads.php, package-lock.json, package.json
Implements the `NEWSPACK_AMP_PLUS_ADS_DISABLED` flag to opt-out of AMP Plus.
Allows for AMP Plus features to be used on the Newspack ecosystem without necessarily activating it for Ads.
It also simplifies the method to remove `class_exists()` for `\Newspack\AMP_Enhancements`. The `method_exists()` function already performs the necessary checks to avoid missing class errors.
ef1441952228f763e9efe40839db62cda2514755 removes an unnecessary duplicate logic
1. Check out this branch with AMP installed and the AMP Plus flag (`NEWSPACK_AMP_PLUS_ENABLED`) confirm you are still able to see Ads rendered through GPT (inspect the Ad element and confirm it is not a `<amp-ad />` element)
2. Add `define( 'NEWSPACK_AMP_PLUS_ADS_DISABLED', true );` to your `wp-config.php` and refresh the page
3. Confirm …
=> feat: constant to opt-out of AMP Plus

includes/providers/gam/class-gam-model.php, tests/test-model.php
Implements permanent default ad units. #410 proposes that the default ad units can be edited and saved to be part of the publisher's inventory. This can overcomplicate how we manage the ad units, this PR proposes the default ad units are permanent and not editable.
Closes #410 
1. Check out this branch and https://github.com/Automattic/newspack-plugin/pull/1654
2. With a fresh install, use legacy mode by just entering a GAM network code
3. Visit the GAM wizard and observe the uneditable default ad units
4. Visit the placements wizard, select edit a placement and confirm you are able to select and save a default ad unit
5. Edit a page, add an ad unit block and confirm you are able to select and save a default ad unit
6. Confirm the slot is configured on the front-end for both AMP and AMP …
=> feat(gam): default ad units

includes/class-core.php, includes/class-placements.php, includes/integrations/class-scaip.php, includes/providers/gam/class-gam-model.php, tests/test-model.php
Implements the following activation defaults, if the settings are not yet found on the database:
- Default ad units assigned to their respective placements
- SCAIP with the legacy option turned off (legacy should still be the default option for users that were already using Ads with SCAIP)
- SCAIP number of repetitions set to 3 in order to use use all 3 in-article default ad units
Closes #411
1. On a fresh install, check out this branch
2. Go through the onboarding wizard and activate the Ads plugin
3. Enable GAM and enter a legacy network code
4. Visit the Placements wizard and confirm the active placements have a default unit assigned to them
5. Visit the Add-Ons wizard and enable SCAIP
6. Visit the Settings wizard and confirm legacy mode is off and the number of repetitions is set to 3 …
=> feat: activation hook defaults

includes/providers/gam/class-gam-model.php, tests/test-model.php
The optimistic release merge from 8f5afd3b8b354e6dc7bba1bac2ec91631ac2032e replaced code from the still unreleased #406
This PR fixes those conflicts and I also took the opportunity to refactor it a little bit for better readability.
Repeat steps from #428 and confirm it behaves as expected.
=> fix(gam): refactor ad units getter sync strategy

includes/providers/gam/class-gam-api.php
Adds caching of the OAuth credentials object. The code on `master` requests the credentials a few times per request, so when the OAuth token needs to be refreshed, it would be refreshed a few times concurrently.   
This PR adds caching of the (successful) credentials retrieval. 
1. Change the expiration date (`expires_at`) of the `_newspack_google_oauth` option's value, or wait an hour after connecting Google for the token to expire
1. On `master`, set `NEWSPACK_LOG_LEVEL` to `2` and observe the logs
2. Load the Advertising wizard and observe that the google proxy is hit four times (`authenticate_proxy_url` called)
3. Switch to this branch, observe the proxy is only hit once
=> fix(oauth): cache oauth credentials

includes/integrations/class-bidding-gam.php, includes/providers/gam/class-gam-api.php, includes/providers/gam/class-gam-model.php
An available service account credential should be prioritized because it can be considered as a more stable connection than an OAuth token with an expiration date. This PR implements this change and removes the `can_use_service_account()` check because a service account connection method should always be available for a disconnected client.
The Google Ads SDK was also updated to the latest version.
1. Check out this branch and https://github.com/Automattic/newspack-plugin/pull/1694
2. Make sure your instance can use OAuth and connect with Google OAuth
3. Visit the GAM ad units wizard and confirm you see the synced ad units and the Service Account connection method at the bottom is **not** available
4. At the "Connections" page, disconnect from Google
5. Visit the wizard again and confirm …
=> fix(gam): prioritize service account and other tweaks

includes/class-blocks.php, includes/class-placements.php, includes/class-suppression.php, includes/customizer/class-customizer.php, includes/customizer/class-placement-customize-control.php, includes/providers/broadstreet/class-broadstreet-provider.php, includes/providers/gam/class-gam-model.php, includes/providers/gam/class-gam-provider.php, includes/providers/gam/class-gam-scripts.php, src/blocks/ad-unit/edit.js, src/blocks/ad-unit/editor.scss, src/blocks/ad-unit/index.js, src/customizer/control.js, src/frontend/style.scss, src/placements/placement-control.js, src/suppress-ads/index.js
Implements optional fixed height for ad placements.
Editing a placement from the wizard:
Editing a block (dynamic placement):
Editing a placement from the customizer:
Since Broadstreet zones only support one size, a simple div with a fixed height will contain the ad.
To handle a variety of cases, the handling of fixed height occurs in two steps:
1. A server-side rendered `<style />` applies media queries with height rules following the _viewport -> sizes_ map returned from [`get_ad_unit_size_map()`](https://github.com/Automattic/newspack-ads/blob/c394b4b9460c49862e26fb067009f26d1772b6a4/includes/providers/gam/class-gam-model.php#L759)
2. To handle the odd case of altered size map from bounds containers, the height is dynamically readjusted as soon as the frontend-calculated bounds …
=> feat(placements): fixed height support

CHANGELOG.md, includes/class-blocks.php, includes/class-placements.php, includes/class-providers.php, includes/customizer/class-placement-customize-control.php, includes/providers/broadstreet/class-broadstreet-provider.php, includes/providers/gam/class-gam-provider.php, includes/providers/interface-provider.php, newspack-ads.php, package-lock.json, package.json, src/blocks/ad-unit/edit.js, src/blocks/ad-unit/index.js, src/customizer/control.js, tests/class-newspack-ads-test-provider.php
The current implementation of the default provider assumes that GAM is always active and considered default. This causes unexpected behavior when Broadstreet is the only active provider and a placement does not include the `provider` attribute.
This PR fixes two issues:
- Make sure GAM is active before using it as default. If not, the first active provider will be considered the default.
- When placing an ad unit block with only 1 active provider, ensures the provider attribute is set to not rely on the default provider
- On the master branch, disable the GAM provider and enable Broadstreet
- Attempt to place an ad unit block with a Broadstreet unit and confirm the ad unit does not render on the page
- Also confirm that the "Save" button is greyed out because the provider is not set on …
=> fix: handling of default provider when GAM is not active

includes/providers/broadstreet/class-broadstreet-provider.php, src/frontend/style.scss
This PR fixes AMP responsive ads for the Broadstreet provider. We're forcing the layout to `fixed` because of CSS incompatibility on how Broadstreet handles different viewports for the ad. A few CSS tweaks are enough to allow the default `responsive` layout to work as expected.
1. Check out this branch and make sure you have AMP on
2. Make sure you have the Broadstreet provider configured
3. Set a Broadstreet unit to a global placement and visit the page
4. Confirm the ad renders as expected
5. Reload the page on mobile viewport
6. Confirm the ad is resized to fit the viewport
=> fix(broadstreet): amp responsive ads

.prettierrc, package-lock.json, package.json, src/blocks/ad-unit/editor.scss, src/frontend/style.scss, src/suppress-ads/index.js
Similar to https://github.com/Automattic/newspack-theme/pull/1845 and https://github.com/Automattic/newspack-blocks/pull/1174, updates prettier, stylelint and Newspack scripts to the latest versions:
* `newspack-scripts@4.0.3` was added
* `wp-prettier` (aliased to prettier) were updated
* styles were migrated with `npx sass-migrator module src/**/*.scss`
* styles were fixed with `npm run lint:scss -- --fix`
* JS was fixed with `npm run lint:js -- --fix`
Like https://github.com/Automattic/newspack-newsletters/pull/894, I prefixed all variables coming from `~@wordpress/base-styles/colors ` with `wp-colors` instead of `colors` -- though there's no need to differentiate these Sass colour variables from Sass colour variables from the plugin, it helps make the prefixing consistent across the …
=> chore(deps): update newspack-scripts, prettier

CHANGELOG.md, includes/class-placements.php, includes/providers/broadstreet/class-broadstreet-provider.php, newspack-ads.php, package-lock.json, package.json, src/blocks/ad-unit/edit.js, src/frontend/style.scss
Properly handle Broadstreet zones without a fixed size. It's currently assumed that all zones will have a size and it causes zones without size to be rendered with `width` set to `0`.
1. Setup Broadstreet
2. Create a zone without a fixed size
3. Attach an ad to this zone through a campaign
4. Set this zone to an ad placement
5. Visit the page and make sure the ad is rendered
=> fix(broadstreet): allow units without fixed sizes

includes/integrations/class-bidding-gam.php, includes/providers/gam/class-gam-model.php
This PR fixes the usage of `usort()` to return an integer instead of a boolean value.
Closes #498
1. Setup GAM connection and header bidding support*
2. Create a new header bidding GAM order through Advertising -> Settings
3. Confirm the order is created without errors
* `define( 'NEWSPACK_EXPERIMENTAL_READER_ACTIVATION', true );` in your `wp-config.php` file
1. Setup GAM with AMP and ad units containing multiple sizes for responsive ads
2. Visit the frontend and confirm the AMP ad renders as expected
3. Change your viewport and confirm the rendered ad is updated as expected
=> fix: usort() usage to return int instead of bool

includes/class-core.php, includes/class-settings.php, includes/integrations/class-ad-refresh-control.php, includes/providers/gam/class-gam-lazy-load.php, includes/providers/gam/class-gam-lazy-loading.php, includes/providers/gam/class-gam-scripts.php
For better maintainability, this PR moves the GAM lazy load settings to its own class and script. It also hides settings that are not supported under AMP.
Closes #494 
1. Visit the Advertising -> Add-Ons and make sure "Ad Refresh Control" is active
2. Make sure AMP is on (without AMP Plus) and visit "Advertising -> Settings"
3. Confirm you only see the "Custom Ad Label" section (or SCAIP settings as well, if installed)
4. Enable AMP Plus, refresh the page and confirm you also see Lazy Load and Refresh Control sections
1. With AMP Plus on, enable lazy load and tweak the settings
2. Place some ad units and visit the frontend
3. Inspect the DOM and search for `lazy_load` and confirm you see this script rendered:
```js
( function() {
var lazy_load = …
```
=> fix: reorganize amp restricted settings

CHANGELOG.md, includes/class-core.php, includes/providers/gam/class-gam-ad-block-recovery.php, newspack-ads.php, package-lock.json, package.json
Implements GAM's Ad Block Recovery messaging, provided by Funding Choices.
Closes #505 
Since Funding Choices require URL approval, there's no way of testing the rendering of the recovery messaging.
1. Make sure you have AMP on and AMP Plus **off**
2. Visit the Advertising -> Settings wizard
3. Confirm you **can't** see the "Ad Block Recovery" section
4. Enable AMP Plus
5. Refresh the settings and confirm the new section
6. Enable the section, paste and save the following values for `pub` and `nonce` respectively:
1. `8706684637650171`
2. `MNc-oZaqRW2VBOls3yFxoA`
7. Visit the frontend, inspect the page and search for the `pub` value
8. Confirm you see the rendered script:
```html
<script data-amp-plus-allowed="" async="" src="https://fundingchoicesmessages.google.com/i/pub-8706684637650171 …
```
=> feat(gam): ad block recovery

includes/providers/gam/class-gam-ad-block-recovery.php
If never saved, the value of `$settings` here may be empty. In this case, the `$settings['active']` check will cause a PHP notice to be logged.
=> fix: handle empty settings section

includes/providers/gam/class-gam-model.php
Fixes an issue with `0x0` ad unit size, which is possible to create. 
1. Create an ad unit with size of 0 by 0
2. Use it in a placement
3. On `master`, observe a PHP Warning about division by zero logged
4. Switch to this branch, observe no warning
=> fix: handle zero in ad unit size gracefully

.circleci/config.yml, composer.json, composer.lock, tests/test-bidding.php, tests/test-model.php, tests/test-providers.php
This upgrades the tests so they can run both on php 7.4 and 8.
To test it, load the repo in a php 8 environment and run composer install. the run ./vendor/bin/phpunit
Do the same thing on a php 7.4 environment, but run composer update instead of install. (Discard the changes to composer.lock afterwards)
=> test: Upgrade to php 8

includes/providers/gam/api/class-ad-units.php, includes/providers/gam/api/class-api.php, includes/providers/gam/class-gam-model.php
Default GAM ad units are currently treated as a static configuration. They are available for usage but are not located in any database or synced to GAM.
This PR implements GAM synchronization if possible. In case a GAM connection is not available, the default static behavior is preserved.
Closes #454
1. Make sure your instance is disconnected from GAM
2. Check out this branch and visit the Advertising dashboard
3. Confirm you can use the static default ad units
4. Connect your instance with GAM
5. Visit the ad units configuration and confirm the units are no longer "default units" and you can edit them
6. Visit your GAM dashboard and confirm the units are created
7. Disconnect from GAM again
8. Confirm the default units are still treated as GAM items, but "Disconnected from GAM"
=> feat(gam): sync default ad units

includes/class-placements.php
This PR removes the handling of a deprecated option name. This has been up for almost 1 year and automatically migrating placement data if the deprecated option is found.
It's safe to remove this and stop querying the database with non-existing options.
No change should take place, ad placements should continue to render as expected.
=> fix(placements): remove deprecated option handling

includes/providers/gam/api/class-api.php, includes/providers/gam/class-gam-model.php
This PR ensures that the API session is valid before attempting to fetch objects.
1. Make sure you are on the **master** branch
2. Connect through Service Account or OAuth with an account that doesn't have access to any GAM account
3. Visit the Advertising wizard and confirm the fatal error
4. Visit the WP's Customizer and also confirm the fatal error
5. Check out this branch, refresh the wizard and the Customizer
6. Confirm there are no fatal errors and GAM is being treated as disconnected/unavailable
In the future, we can handle messaging to notify that the session doesn't connect to any GAM account. For now, let's just avoid the fatal errors.
=> fix(gam): validate api session

CHANGELOG.md, includes/providers/gam/api/class-api.php, newspack-ads.php, package-lock.json, package.json
#551 surfaced an issue in which the network code for a GAM session may not always be available and they are required for most requests.
This PR ensures that if a network code is not yet set, it'll fetch from the top of the list to fulfill required requests.
The issue only occurs for fresh instances connecting GAM for the first time because the network code is not yet known.
1. Make sure you're on the `release` branch
2. On a fresh install, upload a **valid** GAM service account credential
3. Confirm nothing happened (the request that validates the session couldn't fulfill because the network code is not yet known)
4. Check out this branch and confirm it's connected
=> fix(gam): ensure api requests are made with network code

bin/install-wp-tests.sh, includes/class-core.php, includes/class-placements.php, includes/marketplace/class-marketplace.php, tests/bootstrap.php, tests/test-marketplace.php
This PR implements the ad product as a custom WooCommerce product as part of the marketplace project. This and future PRs for this project should be merged into `epic/marketplace`.
The ad product will be initially defined with a CPD (cost per day) and its orders configured as sponsorships with a flat fee. The advertiser should be able to purchase a range of dates for the sponsorship to last (yet to be implemented).
The ad product configuration consists of:
- Placements (required at least one)
- Required sizes (required at least one)
- Cost per day
The available placements are gathered from the active placements and their configuration. The selection of placements will determine the available sizes, which should all be available for the advertiser to upload creatives.
The proposed UI is a …
=> feat(marketplace): product creation

includes/class-core.php, includes/class-fixed-height.php, includes/class-placements.php, includes/customizer/class-placement-customize-control.php, includes/providers/broadstreet/class-broadstreet-provider.php, includes/providers/gam/class-gam-model.php, includes/providers/gam/class-gam-provider.php, includes/providers/gam/class-gam-scripts.php, src/blocks/ad-unit/index.js, src/customizer/control.js, src/frontend/style.scss, src/placements/placement-control.js
Changes how the "fixed height" system, implemented in #439, behaves. It's currently set as a per-placement setting and this PR turns it into a global setting with max height support:
If "max height" is enabled, any creative rendering above the defined threshold will cause a layout shift (CLS).
1. Checkout this branch and https://github.com/Automattic/newspack-plugin/pull/2255
2. Visit **Advertising -> Settings** and confirm you see the new "Fixed height" section with the above defaults
3. Make sure you have GAM configured and set the Below Header and Footer placements with units containing the sizes: 728x90 970x90 970x250
4. Visit the home page and confirm the CLS occurring from 100 to 250 if the slot renders the 970x250 creative
5. Refresh until a creative with a height of 90px renders …
=> feat: "fixed height" a global setting with max threshold

includes/providers/gam/api/class-api.php, includes/providers/gam/class-gam-model.php
This PR restores proper error messages in the dashboard UI and separates the types of GAM API errors while initializing. The fatal error (environment incompatibility) is irrecoverable and is thrown while instantiating the API. A session error comes from `API->init()` and can be recovered by submitting valid credentials.
Closes #560
1. Check out this branch and https://github.com/Automattic/newspack-plugin/pull/2289
2. Visit the Advertising dashboard and if you are not connected, confirm the "missing credentials" error
3. If you are connected, disconnect to confirm the message
4. Connect again and confirm you are connected and without any message
5. Disconnect once more
6. Install the [Constant Contact Form](https://wordpress.org/plugins/constant-contact-forms/) plugin to trigger the …
=> fix(gam): handle API fatal and session errors

includes/providers/broadstreet/class-broadstreet-provider.php
This PR disables "fixed height" support for Broadstreet due to unexpected results of rendered creatives sizes and zone sizes. Creatives can be larger than their defined zone size.
1. Make sure you have Broadstreet configured and "fixed height" enabled
2. Place a Broadstreet zone above the fold
3. Visit the page and confirm fixed height does not apply and you get CLS on the creative render
=> fix(broadstreet): disable "fixed height" support

includes/class-placements.php, includes/providers/gam/class-gam-scripts.php
The recent implementation of default fixed height for placements surfaced an issue with how the suppression for ads is applied when the provider is not active.
The suppression currently occurs only at the provider code level. The placement code is still applied and results in an empty div. This div is still processed by the fixed height CSS and results in a blank space.
This PR ensures the placement doesn't render any markup as well as the fixed height CSS.
1. Confirm the issue in master by configuring placements with GAM active
2. Disable GAM, visit the frontend, and confirm the blank spaces
3. Checkout this branch, refresh, and confirm the units are not rendered
4. Enable GAM, refresh, and confirm the units are rendered again with proper fixed height
=> fix(placements): suppress render for inactive providers

src/blocks/ad-unit/edit.js
Fix the usage of `useEffect` cleanup function.
Related: https://github.com/Automattic/newspack-plugin/issues/2269 https://github.com/Automattic/newspack-plugin/pull/2335
1. Check out this branch
2. Add a new Ad Unit block to a post
3. Make sure you are able to select the unit and save
4. Visit the front end and confirm the unit is rendered without issues
=> fix: proper usage of useEffect cleanup function

includes/providers/gam/api/class-api.php, includes/providers/gam/class-gam-model.php
This PR ensures that a connected Google OAuth account that doesn't have access to any GAM networks is properly handled without throwing 500 errors.
Closes #621 
1. Checkout this branch and make sure you have Google OAuth support using NM's proxied connection (ping me for instructions)
2. Connect to an account that is not connected to any GAM network
3. Visit the Ads wizard and confirm the error message as in the image above and #621 is no longer reproducible
=> fix(gam): handle account without networks

includes/providers/gam/class-gam-scripts.php
Move the non-AMP sticky ads handling from [Newspack Theme](https://github.com/Automattic/newspack-theme/blob/1dfb96be14281347ca155115a92079c31b4c59c6/newspack-theme/js/src/amp-plus.js#L16-L46) to here.
Pushing as a hotfix because [sites without AMP or AMP Plus currently have no handling of the sticky ads](https://github.com/Automattic/newspack-theme/blob/1dfb96be14281347ca155115a92079c31b4c59c6/newspack-theme/functions.php#L451-L464), making them non-dismissable.
1. While in the master branch, make sure you don't have AMP or the AMP Plus flag
2. Place a sticky ad and confirm on mobile viewport that you are unable to dismiss it (clicking on the X does nothing)
3. Check out this branch and confirm the ad can be dismissed
4. Refresh the page, scroll down, and confirm there's padding applied …
=> fix(gam): handle sticky ads without amp

includes/providers/gam/api/class-ad-units.php, includes/providers/gam/api/class-advertisers.php, includes/providers/gam/api/class-api.php, includes/providers/gam/api/class-creatives.php, includes/providers/gam/api/class-line-items.php, includes/providers/gam/api/class-orders.php, includes/providers/gam/api/class-targeting-keys.php
Updates the GAM API version from `v202208` to `v202305`.
1. Install this branch on a fresh install
2. Connect to GAM using a service account or through Google OAuth
3. Confirm the account's ad units are synced
4. Create a new ad unit, and confirm it's created on the ad manager's dashboard
5. Archive the created ad unit and confirm it's archived on the ad manager's dashboard
=> fix(gam): update api version

includes/providers/gam/api/class-ad-units.php, includes/providers/gam/class-gam-scripts.php
Implements support for parent ad unit path when configuring the slots.
Closes #493 
1. Check out this branch and https://github.com/Automattic/newspack-plugin/pull/2592
2. Make sure you have GAM configured
3. Navigate to your GAM dashboard and create a child ad unit, through Inventory -> Ad Units and click "+ Add child ad unit":
4. In WP dashboard, visit Newspack -> Advertising -> Configure GAM
5. Locate the created unit and click to edit
6. Confirm the code includes the parent unit code in its path
7. Visit "Placements", apply the new child unit to a global placement
8. Visit the front-end with the `?googfc` URL parameter
9. Locate the new unit in the console and confirm the code includes the parent path
=> feat(gam): support parent ad unit path

includes/providers/gam/api/class-ad-units.php
Not sure how to force `getParentPath` to return `null` because [according to the docs it should always return an array (and an empty array if there is no parent)](https://developers.google.com/ad-manager/api/reference/v202305/InventoryService.AdUnit#parentpath). It can happen somehow though! If it does, we don't want fatal errors.
=> fix: dont throw fatals if parentPath is null

includes/providers/gam/api/class-api.php, includes/providers/gam/class-gam-model.php
Validate the stored network code while creating the GAM API session. This change prevents user/credentials from getting stuck with an invalid network code when the connected account is updated.
It also adds cache deletion on option updates to prevent the 'notoptions' bug on memcache.
1. While on the master branch, make sure you are connected to GAM
2. Manually change `_newspack_ads_service_google_ad_manager_network_code` and `_newspack_ads_gam_network_code` to an invalid value:
```
wp option update _newspack_ads_service_google_ad_manager_network_code "1"
wp option update _newspack_ads_gam_network_code "1"
```
3. Refresh the Advertising dashboard and confirm you get the "**The network code is invalid.**" error
4. Check out this branch, refresh, and confirm the error is gone and the network …
=> fix(gam): validate network code on session creation

includes/providers/gam/class-gam-scripts.php
Move part of the sticky ad handling so it's inside the ad units loop.
1. Confirm sticky ad testing works by following instructions at https://github.com/Automattic/newspack-ads/pull/641
2. Disable all placements from your site, visit the frontend, and confirm there's no error thrown from the script
=> fix: sticky ad handling

includes/providers/gam/class-gam-model.php
If the found synced GAM ad unit is at index `0` it will be ignored by the current check and cause a faulty ad unit collection:
This PR fixes the index check by doing a strict comparison to `false`.
=> fix(gam): default units array search matching

includes/marketplace/class-api.php, includes/marketplace/class-email.php, includes/marketplace/class-marketplace.php, includes/marketplace/class-product.php
Implements support for custom email notifications on marketplace orders.
1. Check out this branch and https://github.com/Automattic/newspack-plugin/pull/2628
2. Make sure you are connected to a GAM account and have marketplace products created (see https://github.com/Automattic/newspack-ads/pull/566)
3. Visit Advertising -> Marketplace -> Settings
4. Confirm it renders as in the image above
5. Set a custom email and save
6. Make sure you have "New Order" emails enabled in WC (per form instruction)
7. Edit a new page and add the "Marketplace" block, which renders only a placeholder component in the editor
8. Visit the page, select a product, a valid date range (cannot be starting Today), and upload creatives that match the ad product requirements of size (see …
=> feat(marketplace): email settings

includes/providers/gam/api/class-api.php
Prevents the following warning coming from GAM's SDK:
```
PHP Warning:  Network code is not specified. An API function will reject requests if it requires a network code.
```
This request is sent without a network code on purpose because it's fetching which network code it'll use.
1. While on the master branch, confirm you're connected to GAM and visit the Advertising dashboard
2. Confirm you see the warning in your logs
3. Check out this branch, refresh the page and confirm there are no warnings
=> fix(gam): silence network code check warning

includes/providers/gam/class-gam-scripts.php
Cached ad units may not include the 'path' property. This prevents from this throwing a warning.
GAM ads should continue to render without issues or server warnings.
=> fix(gam): handle missing ad unit 'path'

newspack-ads.php
Updates some lingering legacy URLs throughout the code. All instances of newspack.pub or newspack.blog should be newspack.com
No functional changes.
=> chore: newspack.pub > newspack.com

includes/providers/gam/api/class-api.php
Deprecated in PHP 8.2
To test, switch to PHP 8.2 and observe a `Using ${var} in strings is deprecated […]` warning is logged.
=> chore: fix usage of interpolated variable

includes/integrations/class-bidding-gam.php
- Replace deprecated FILTER_SANITIZE_STRING with FILTER_SANITIZE_FULL_SPECIAL_CHARS to maintain PHP 8.1 compatibility.
6453 | preprod | preprod | 2023-10-23T12:30:23.139443119Z | PHP message: PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /var/www/wp-content/plugins/newspack-ads/includes/integrations/class-bidding-gam.php on line 325
-- | -- | -- | -- | --
- WP 6.3.2
- PHP 8.1
- WP VIP Site
=> 🛠️ Update Deprecated Constant: FILTER_SANITIZE_STRING

includes/class-core.php
If the page should not display ads, don't enqueue CSS. 
1. Visit a page that will display ads, observe that `frontend.css` file is downloaded
2. Visit a page that has ads disabled, observe that the file is not downloaded
=> feat(perf): don't enqueue CSS if ads are not to be displayed

includes/providers/gam/api/class-targeting-keys.php, includes/providers/gam/class-gam-model.php
Implements "site" custom targeting key-val with type "PREDEFINED" and reportable type set to "CUSTOM_DIMENSION".
The `Targeting_Keys::update_default_targeting_keys()` method was also updated to use the `Targeting_Keys::create_targeting_key()` method instead of its own logic for better maintenance.
1. If you have the `site` targeting key already created, visit your GAM Inventory -> Key-values, edit and delete each value, then delete the key (mind that GAM never deletes an entity, it's only archived)
3. Make sure you are connected to a GAM account in your Newspack instance
4. Check out this branch, visit Newspack -> Advertising, and confirm the targeting key is created:
5. Visit your GAM inventory and confirm the `site` is created with the previously available values plus your instance's …
=> feat(gam): support "site" custom targeting key-val

includes/class-settings.php, includes/customizer/class-customizer.php
Adds filtering of admin panel access. This will be used by upcoming changes in the Newspack Plugin, which will introduce granular capabilities management. 
1. There should be no functional changes for end users, this is a backend feature. Verify that Newspack Advertising wizard can still be accessed as an admin* user 
\* a user with `manage_options` capability
=> feat: filter for settings access

includes/providers/gam/class-gam-model.php
1200550061930446-as-1206445581284648
The "site" targeting key-val for GAM is created with pre-defined values that are sanitized. The targeting in the slot is currently missing the sanitization. This PR sanitizes the URL that is sent to the ad slot.
1. While on the `release` branch, make sure you have a GAM ad rendered on your site
2. Visit the page with an ad with the `?googfc` query param
3. Open the targeting info for the slot and confirm the "site" value includes the URL protocol and possibly trailing slash
4. Check out this branch, refresh and confirm it doesn't include protocol or trailing slash
=> fix(gam): sanitize URL for "site" targeting key-val
